stateDiagram-v2
    ChainOpenWorkspace --> ChainBuildNodeTable
    ChainBuildNodeTable --> ChainEnsureKeys
    ChainEnsureKeys --> ChainEnsureKeysFromPreset
    ChainEnsureKeys --> ChainEnsureKeysGenerated
    ChainEnsureKeys --> ChainEnsureKeysFromBlueprint
    ChainEnsureKeysFromPreset --> ChainBuildGenesis
    ChainEnsureKeysFromPreset --> ReconcileChain
    ChainEnsureKeysGenerated --> ChainBuildGenesis
    ChainEnsureKeysGenerated --> ReconcileChain
    ChainEnsureKeysFromBlueprint --> ChainBuildGenesis
    ChainEnsureKeysFromBlueprint --> ReconcileChain
    ReconcileChain --> ReconcileChainAllKept
    ReconcileChain --> ReconcileChainSomeRedone
    ReconcileChainAllKept --> ChainBuildGenesis
    ReconcileChainSomeRedone --> ChainBuildGenesis
    ChainBuildGenesis --> ChainBuildGenesisFromTemplate
    ChainBuildGenesis --> ChainBuildGenesisFromExisting
    ChainBuildGenesisFromTemplate --> ChainBuildGenesisForkApplied
    ChainBuildGenesisFromTemplate --> ChainBuildGenesisVariantsWritten
    ChainBuildGenesisFromTemplate --> ChainBuildNodeConfig
    ChainBuildGenesisFromExisting --> ChainBuildGenesisForkApplied
    ChainBuildGenesisFromExisting --> ChainBuildGenesisVariantsWritten
    ChainBuildGenesisFromExisting --> ChainBuildNodeConfig
    ChainBuildGenesisForkApplied --> ChainBuildGenesisVariantsWritten
    ChainBuildGenesisForkApplied --> ChainBuildNodeConfig
    ChainBuildGenesisVariantsWritten --> ChainBuildNodeConfig
    ChainBuildNodeConfig --> ChainBuildNodeCommand
    ChainBuildNodeCommand --> ChainDeployNodes
    ChainDeployNodes --> ChainInitNodes
    ChainDeployNodes --> ChainDeployNodesVerifiedLocal
    ChainDeployNodes --> ChainDeployNodesShippedRemote
    ChainDeployNodesVerifiedLocal --> ChainInitNodes
    ChainDeployNodesShippedRemote --> ChainInitNodes
    ChainInitNodes --> ChainLaunchNodes
    ChainLaunchNodes --> ChainLaunchNodesPhaseLaunching
    ChainLaunchNodesPhaseLaunching --> ChainLaunchNodesPhaseActions
    ChainLaunchNodesPhaseLaunching --> ChainLaunchNodesPhaseDone
    ChainLaunchNodesPhaseActions --> ChainLaunchNodesPhaseDone
    ChainLaunchNodesPhaseDone --> ChainLaunchNodesPhaseLaunching
    ChainLaunchNodesPhaseDone --> ChainVerify
    ChainVerify --> ChainVerifyProducing
    ChainVerify --> ChainVerifyHaltedAsDeclared
    ChainVerifyProducing --> ChainReady
    ChainVerifyHaltedAsDeclared --> ChainReady
    AdoptChain --> AdoptChainByRPC
    AdoptChain --> AdoptChainByWorkspace
    AdoptChain --> AdoptChainByDeclaration
    AdoptChainByRPC --> CompareChain
    AdoptChainByWorkspace --> CompareChain
    AdoptChainByDeclaration --> CompareChain
    CompareChain --> CompareChainSame
    CompareChain --> CompareChainNodesDiffer
    CompareChain --> CompareChainNetworkDiffers
    CompareChain --> CompareChainNothingComposed
    CompareChainSame --> ChainVerify
    CompareChainNodesDiffer --> ChainVerify
    CompareChainNetworkDiffers --> ChainOpenWorkspace
    CompareChainNothingComposed --> ChainOpenWorkspace