# -*- coding: utf-8 -*-
"""세 체인 공통 테스트 목록(CT ID) 정본. 렌더러(render_pages.py)가 이 데이터로 페이지를 만든다.

필드
- id / area / name : CT ID, 영역, 이름
- purpose          : 무엇을 확인하는지 한 문장
- steps            : 실행 절차(공통)
- expected         : 세 체인이 같이 만족해야 하는 기대 결과
- diff             : 체인별로 다른 점. 없으면 빈 문자열
- deps             : 의존 요소 태그 (계정, RPC, 컨트랙트, ChainID, 포크, 수수료, 토폴로지, 바이너리, 프로세스)
- sep              : 분리 방식. '설정' | '설정+기대값' | '별도 구현'
- spec             : 기존 명세 ID (StableNet RT-/TC-, WEMIX4.0 TX-/RPC-/NODE-, WEMIX3.0, 2차 변경 T-)
- auto             : chainbench 자동 테스트 실행 ID
- pr196            : PR196 144개 목록의 우선순위(P0~P3). 없으면 None
- note             : 비고
"""

CT = [
# ---------------------------------------------------------------- NODE
dict(id='CT-NODE-001', area='NODE', name='노드 기동과 블록 생성',
     purpose='세 체인 각각 노드를 띄웠을 때 블록이 만들어지고 노드끼리 연결되는지 확인한다.',
     steps=['블록 생성 노드 4대로 네트워크를 띄운다.', '블록 높이가 2 이상이 될 때까지 기다린다.', '체인 ID, 블록 높이, 연결된 피어 수를 조회한다.'],
     expected='체인 ID가 설정값과 같다. 블록 높이가 2 이상이다. 피어 수가 0이 아니다.',
     diff='WEMIX4.0과 StableNet은 검증자 목록 조회로 생산자 수를 함께 확인할 수 있다. WEMIX3.0은 해당 조회가 없어 관리 API로 확인한다.',
     deps=['ChainID','토폴로지','바이너리','RPC'], sep='설정+기대값',
     spec=[], auto=['wemix-chain-up','wbft-chain-up','stablenet-chain-up'], pr196='P1',
     note='검증자 수 확인은 체인마다 방법이 다르다.'),
dict(id='CT-NODE-002', area='NODE', name='15노드 구성 기동',
     purpose='블록 생성 노드 13대와 전달·종단 노드로 큰 구성을 띄웠을 때도 블록이 만들어지는지 확인한다.',
     steps=['블록 생성 노드 13대, 전달 노드 1대, 종단 노드 1대로 네트워크를 띄운다.', '블록 높이가 2 이상이 될 때까지 기다린다.', '체인 ID, 블록 높이, 피어 수를 조회한다.'],
     expected='CT-NODE-001과 같다. 검증자 수가 13이다(WEMIX3.0은 검증자 조회가 없어 생략).',
     diff='WEMIX3.0은 전달 노드 없이 종단 노드 2대 구성을 쓴다. 기동 대기 시간이 더 길다.',
     deps=['토폴로지','바이너리','RPC'], sep='설정+기대값',
     spec=[], auto=['wemix-chain-up-15','wbft-chain-up-15','stablenet-chain-up-15'], pr196='P1',
     note=''),
dict(id='CT-NODE-003', area='NODE', name='제네시스 초기화와 블록 0 해시 일치',
     purpose='제네시스 파일로 초기화한 모든 노드의 블록 0 해시가 같고, 체인 ID가 제네시스 값과 같은지 확인한다.',
     steps=['체인별 제네시스로 모든 노드를 초기화하고 기동한다.', '각 노드에서 블록 0을 조회한다.', '체인 ID를 조회한다.'],
     expected='모든 노드의 블록 0 해시가 같다. 블록 0의 이전 블록 해시가 0이다. 체인 ID가 제네시스 값과 같다.',
     diff='WEMIX3.0은 제네시스를 노드 프로그램이 거버넌스 설정에서 만든다. WEMIX4.0과 StableNet은 템플릿에 검증자 정보를 채워 만든다. 기대 해시는 체인·구성마다 다르다.',
     deps=['ChainID','바이너리','토폴로지'], sep='설정+기대값',
     spec=['RT-A-1-01','RT-A-1-01-B','TC-5-3-01','TS-5-3-01'], auto=['genesis-block-hash-consistent','chain-id'], pr196='P1',
     note='RT-A-1-01-A(테스트넷 내장 제네시스)는 StableNet 전용이라 제외.'),
dict(id='CT-NODE-004', area='NODE', name='Full Sync 동기화',
     purpose='새 노드가 모든 블록을 실행하며 기존 체인을 따라잡는지 확인한다.',
     steps=['기존 노드의 블록 높이가 새 노드보다 2 이상 높은 상태를 만든다.', '새 노드를 full 동기화 방식으로 기동한다.', '같은 높이에서 블록 해시와 상태 루트를 비교한다.'],
     expected='새 노드의 블록 해시와 상태 루트가 기존 노드와 같다.',
     diff='기본 동기화 방식이 WEMIX3.0은 snap, 나머지 둘은 full이라 방식을 명시해야 한다. WEMIX3.0은 블록 생성 노드끼리 별도 동기화 점검이 끼어들므로 생산에 참여하지 않는 노드에서 관찰한다.',
     deps=['토폴로지','바이너리','프로세스'], sep='설정+기대값',
     spec=['RT-A-1-02','NODE-003'], auto=[], pr196='P0', note=''),
dict(id='CT-NODE-005', area='NODE', name='Snap Sync 동기화',
     purpose='새 노드가 상태 스냅샷으로 동기화한 뒤 잔액 조회가 되는지 확인한다.',
     steps=['기존 체인에 블록 128개 이상을 쌓는다.', '새 노드를 snap 동기화 방식으로 기동한다.', '동기화 완료 후 잔액과 상태 루트를 비교한다.'],
     expected='상태 동기화가 끝나고 잔액 조회가 된다. 상태 루트가 기존 노드와 같다. full 방식으로 바뀌어 끝난 경우는 통과로 보지 않는다.',
     diff='CT-NODE-004와 같다.',
     deps=['토폴로지','바이너리','프로세스'], sep='설정+기대값',
     spec=['RT-A-1-03','NODE-004'], auto=[], pr196='P1', note=''),
dict(id='CT-NODE-006', area='NODE', name='누락 블록 일괄 동기화',
     purpose='연결이 끊겨 블록 격차가 2 이상 생긴 노드가 다시 연결됐을 때 누락 블록을 순서대로 받아오는지 확인한다.',
     steps=['노드 하나를 네트워크에서 분리한다.', '나머지 노드가 블록을 2개 이상 더 만들 때까지 기다린다.', '다시 연결하고 블록 높이가 같아질 때까지 기다린다.', '같은 높이의 블록과 상태를 비교한다.'],
     expected='분리됐던 노드가 누락 블록을 받아 높이와 해시가 일치한다.',
     diff='어느 경로로 받았는지는 노드 로그로 확인한다. 로그 문구가 체인마다 다르다.',
     deps=['토폴로지','프로세스'], sep='별도 구현',
     spec=['RT-A-1-06'], auto=[], pr196='P0', note=''),
dict(id='CT-NODE-007', area='NODE', name='새 블록 실시간 수신',
     purpose='정상 운영 중인 노드가 다른 노드가 만든 새 블록을 전파로 받아 바로 반영하는지 확인한다.',
     steps=['블록 생성 중인 네트워크에 관찰 노드를 둔다.', '새 블록이 만들어질 때마다 관찰 노드의 블록 높이를 조회한다.'],
     expected='새 블록이 만들어진 직후 관찰 노드의 높이가 따라 올라간다.',
     diff='CT-NODE-006과 같다.',
     deps=['토폴로지'], sep='별도 구현',
     spec=['RT-A-1-07'], auto=[], pr196='P0', note=''),
dict(id='CT-NODE-008', area='NODE', name='피어 연결과 피어 조회',
     purpose='노드들이 부트노드를 거쳐 서로 연결되고, 피어 수와 피어 정보를 조회할 수 있는지 확인한다.',
     steps=['부트노드 설정으로 노드들을 기동한다.', '각 노드에서 피어 수를 조회한다.', '피어 상세 정보를 조회한다.'],
     expected='모든 노드의 피어 수가 1 이상이다. 피어 정보에 상대 노드가 보인다.',
     diff='피어 상세 조회는 관리용 API라 운영망 공개 RPC에서는 닫혀 있을 수 있다.',
     deps=['RPC','토폴로지'], sep='설정',
     spec=['RT-A-1-05','RT-G-4-01','RT-G-4-04','RPC-019'], auto=['basic-peers','admin-peers-populated'], pr196='P1',
     note=''),
dict(id='CT-NODE-009', area='NODE', name='노드 간 최신 블록 해시 일치',
     purpose='운영 중인 모든 노드가 같은 최신 블록을 갖는지 확인한다.',
     steps=['블록 높이가 목표에 이를 때까지 기다린다.', '모든 노드에서 최신 블록 해시를 조회해 비교한다.'],
     expected='같은 높이의 블록 해시가 모든 노드에서 같다.',
     diff='',
     deps=['토폴로지'], sep='설정',
     spec=[], auto=['basic-consensus','basic-sync'], pr196='P1', note=''),
dict(id='CT-NODE-010', area='NODE', name='전달 노드 경유 동기화',
     purpose='종단 노드가 생성 노드와 직접 연결되지 않고 전달 노드만 거쳐도 블록을 받는지 확인한다.',
     steps=['생성 노드, 전달 노드, 종단 노드를 계층으로 연결한다.', '종단 노드의 블록 높이가 올라가는지 확인한다.', '각 노드의 피어 수로 연결 형태를 확인한다.'],
     expected='종단 노드의 높이가 올라간다. 종단 노드의 피어는 전달 노드 하나뿐이다.',
     diff='실행 도구의 WEMIX3.0 구성도 전달 노드 역할을 받는다.',
     deps=['토폴로지'], sep='설정',
     spec=[], auto=['stablenet-proxied-pn-routing','wbft-proxied-routing'], pr196='P2', note=''),
dict(id='CT-NODE-011', area='NODE', name='종단 노드가 먼저 오는 혼합 배치',
     purpose='첫 번째 노드가 종단 노드인 배치에서도 생산자 수가 설정대로인지 확인한다.',
     steps=['종단 노드 1대, 생성 노드 3대를 그 순서로 배치해 기동한다.', '생산자 수를 조회한다.', '블록이 계속 만들어지는지 확인한다.'],
     expected='생산자 수가 3이다. 블록이 계속 만들어진다.',
     diff='생산자 수 조회 방법이 체인마다 다르다(CT-NODE-001 참고).',
     deps=['토폴로지','RPC'], sep='별도 구현',
     spec=[], auto=['e1-mixed-producers'], pr196='P2', note=''),
dict(id='CT-NODE-012', area='NODE', name='노드 프로그램 교체 후 서명 호환',
     purpose='노드 프로그램을 새 버전으로 바꿔도 이전에 처리한 트랜잭션이 그대로 조회되는지 확인한다.',
     steps=['트랜잭션을 보내고 영수증을 저장한다.', '노드 하나의 프로그램을 새 버전으로 바꿔 재기동한다.', '같은 트랜잭션의 영수증과 내용을 다시 조회해 비교한다.'],
     expected='블록 번호, 상태, 보낸 이, 받는 이가 교체 전과 같다.',
     diff='교체할 프로그램 파일과 버전 표기가 체인마다 다르다.',
     deps=['바이너리','프로세스'], sep='별도 구현',
     spec=['TC-3-1-04'], auto=['signature-compat-across-swap'], pr196='P1', note=''),
dict(id='CT-NODE-013', area='NODE', name='제네시스 불일치 시 기동 거부',
     purpose='저장된 체인과 다른 제네시스로 노드를 다시 띄우면 기동을 거부하는지 확인한다.',
     steps=['정상 운영 중인 노드 하나를 멈춘다.', '제네시스 값을 바꿔 다시 띄운다.', '기동 실패 로그를 확인하고 나머지 노드가 계속 블록을 만드는지 본다.'],
     expected='바꾼 노드는 제네시스 불일치로 기동하지 못한다. 나머지 노드는 영향이 없다.',
     diff='제네시스 불일치 오류 문구는 세 클라이언트가 같다(database contains incompatible genesis). 노드를 멈추고 다시 띄우는 제어가 필요해 우리가 띄운 네트워크에서만 된다.',
     deps=['바이너리','프로세스'], sep='별도 구현',
     spec=['TC-4-1-03','TS-4-1-02'], auto=['genesis-mismatch-refuses-to-start'], pr196='P1', note=''),
dict(id='CT-NODE-014', area='NODE', name='동기화 완료 상태 확인',
     purpose='운영 중인 노드가 동기화 중이 아니라고 보고하는지 확인한다.',
     steps=['동기화 상태를 조회한다.'],
     expected='동기화 중이 아니다(false).',
     diff='',
     deps=['RPC'], sep='설정',
     spec=[], auto=['chain-not-syncing','remote-chain-info'], pr196='P2', note=''),
dict(id='CT-NODE-015', area='NODE', name='블록 시각 단조 증가',
     purpose='연속 블록의 시각이 거꾸로 가지 않는지 확인한다.',
     steps=['연속 블록 구간의 시각을 조회한다.', '이전 블록보다 작은 값이 있는지 검사한다.'],
     expected='모든 연속 블록에서 시각이 이전 이상이다.',
     diff='',
     deps=['RPC'], sep='설정',
     spec=['MINING-01'], auto=[], pr196=None, note='WEMIX3.0 시나리오의 관측 부분만 공통으로 가져왔다.'),
dict(id='CT-NODE-016', area='NODE', name='블록 생성 주기',
     purpose='연속 블록의 시각 차이가 설정한 주기와 같은지 확인한다.',
     steps=['연속 블록 3개의 시각을 조회한다.', '차이를 계산해 설정 주기와 비교한다.'],
     expected='시각 차이가 설정 주기와 같다.',
     diff='WEMIX4.0과 StableNet은 기본 1초다. WEMIX3.0은 거버넌스가 정한 간격이라 기대값을 체인별로 둔다.',
     deps=['RPC'], sep='설정+기대값',
     spec=['RT-B-01','WBFT-002'], auto=['block-period-one-second','stress-block-time'], pr196='P1',
     note='명세는 1초 고정이지만 주기를 설정값으로 두면 세 체인에서 쓸 수 있다.'),
# ---------------------------------------------------------------- TX
dict(id='CT-TX-001', area='TX', name='일반 송금',
     purpose='계정 간 송금이 블록에 포함되고 받는 쪽 잔액이 늘어나는지 확인한다.',
     steps=['받을 계정을 새로 만든다.', '노드 계정에서 송금한다.', '영수증과 받는 계정 잔액을 조회한다.'],
     expected='영수증 상태가 성공이다. 받는 계정 잔액이 보낸 금액만큼 늘어난다.',
     diff='',
     deps=['계정','RPC'], sep='설정',
     spec=['TX-001','RT-A-4-03'], auto=['basic-tx-send','sample-minimal-value-transfer','value-transfer'], pr196='P1',
     note='RT-A-4-03은 서명된 트랜잭션 전파 부분만 대응.'),
dict(id='CT-TX-002', area='TX', name='Legacy 트랜잭션',
     purpose='gasPrice 필드만 쓰는 예전 형식 트랜잭션이 처리되는지 확인한다.',
     steps=['gasPrice를 정해 예전 형식으로 서명·전송한다.', '영수증과 트랜잭션 형식을 조회한다.', '보낸 계정 잔액 변화를 계산한다.'],
     expected='상태가 성공이고 형식이 0x0이다. 잔액 변화가 송금액과 수수료의 합과 같다.',
     diff='실제 적용 가스 가격이 StableNet 일반 계정에서는 블록 헤더의 팁으로 바뀐다. 기대 수수료는 체인별로 계산한다.',
     deps=['계정','수수료'], sep='설정+기대값',
     spec=['RT-A-2-01','TX-006'], auto=['legacy-transfer'], pr196='P1', note=''),
dict(id='CT-TX-003', area='TX', name='동적 수수료 트랜잭션',
     purpose='최대 수수료와 팁을 지정하는 형식의 트랜잭션이 처리되는지 확인한다.',
     steps=['최대 수수료를 기본 수수료와 팁의 합 이상으로 정해 전송한다.', '영수증과 형식을 조회한다.'],
     expected='상태가 성공이고 형식이 0x2다. 실제 적용 가스 가격이 규칙대로 계산된다.',
     diff='CT-TX-002와 같다.',
     deps=['계정','수수료'], sep='설정+기대값',
     spec=['RT-A-2-02','TX-003'], auto=['dynamic-fee-tx'], pr196='P1', note=''),
dict(id='CT-TX-004', area='TX', name='접근 목록 트랜잭션',
     purpose='접근 목록을 붙인 트랜잭션이 처리되는지 확인한다.',
     steps=['노드가 만들어 준 접근 목록을 트랜잭션에 붙여 전송한다.', '영수증과 형식을 조회한다.'],
     expected='상태가 성공이고 형식이 0x1이다.',
     diff='',
     deps=['계정','수수료'], sep='설정',
     spec=['RT-A-2-03','TX-007'], auto=['access-list-tx'], pr196='P1', note=''),
dict(id='CT-TX-005', area='TX', name='수수료 대납 트랜잭션',
     purpose='보내는 계정과 수수료를 내는 계정이 다른 트랜잭션이 처리되는지 확인한다.',
     steps=['보낼 계정과 대납 계정을 만들어 자금을 넣는다.', '두 계정이 각각 서명한 대납 트랜잭션을 전송한다.', '영수증과 두 계정의 잔액을 조회한다.'],
     expected='상태가 성공이고 형식이 0x16이다. 보낸 계정은 송금액만 줄고 대납 계정은 수수료만 준다.',
     diff='대납 계정 잔액 검사 기준이 다르다. WEMIX4.0과 StableNet은 조건에 따라 가스 가격 기준으로 검사하고, StableNet은 대납 계정의 차단 여부도 본다.',
     deps=['계정','수수료','포크'], sep='설정+기대값',
     spec=['RT-D-01','TX-004'], auto=['fee-delegated-transfer'], pr196='P1', note=''),
dict(id='CT-TX-006', area='TX', name='대납 트랜잭션의 보낸 이 서명 변조 거부',
     purpose='보낸 이 서명을 조작한 대납 트랜잭션이 거부되는지 확인한다.',
     steps=['정상 대납 트랜잭션을 만든 뒤 보낸 이 서명 값을 바꾼다.', '전송하고 응답을 확인한다.'],
     expected='전송 단계에서 거부된다. 블록은 계속 만들어진다.',
     diff='거부 사유 문구의 앞부분은 같고 뒤에 붙는 설명이 체인마다 다르다.',
     deps=['계정'], sep='설정+기대값',
     spec=['RT-D-03','TX-014'], auto=['fd-sender-sig-invalid-rejected','fee-delegated-sender-sig-invalid-rejected'], pr196='P1', note=''),
dict(id='CT-TX-007', area='TX', name='대납 트랜잭션의 대납자 서명 변조 거부',
     purpose='대납자 서명을 조작한 대납 트랜잭션이 거부되는지 확인한다.',
     steps=['정상 대납 트랜잭션을 만든 뒤 대납자 서명 값을 바꾼다.', '전송하고 응답을 확인한다.'],
     expected='전송 단계에서 거부된다.',
     diff='CT-TX-006과 같다.',
     deps=['계정'], sep='설정+기대값',
     spec=['RT-D-04','TX-015'], auto=['fd-feepayer-sig-invalid-rejected','fee-delegated-feepayer-sig-invalid-rejected'], pr196='P1', note=''),
dict(id='CT-TX-008', area='TX', name='대납자 잔액 부족 거부',
     purpose='대납 계정 잔액이 수수료보다 적으면 거부되는지 확인한다.',
     steps=['잔액이 없는 대납 계정으로 대납 트랜잭션을 전송한다.', '응답과 블록 포함 여부를 확인한다.'],
     expected='거부되고 블록에 포함되지 않는다.',
     diff='StableNet 명세는 실행 단계 거부라고 적었으나 세 클라이언트 모두 풀 진입 단계에서 먼저 거부한다. 잔액 기준(최대 수수료인지 가스 가격인지)이 체인·조건별로 다르다.',
     deps=['계정','수수료'], sep='설정+기대값',
     spec=['RT-D-05','TX-016'], auto=['feepayer-insufficient-rejected','fee-delegated-unfunded-feepayer-rejected'], pr196='P1', note=''),
dict(id='CT-TX-009', area='TX', name='대납 서명 API 존재',
     purpose='대납자 서명을 붙여 주는 API가 노드에 있는지 확인한다.',
     steps=['일부러 잘못된 인자로 대납 서명 API를 호출한다.', '오류가 "메서드 없음"이 아닌지 확인한다.'],
     expected='메서드가 존재한다.',
     diff='',
     deps=['RPC'], sep='설정',
     spec=['RT-G-5-01'], auto=['fee-delegate-sign-rpc-present'], pr196='P3', note=''),
dict(id='CT-TX-010', area='TX', name='접근 목록을 붙인 대납 트랜잭션',
     purpose='접근 목록이 있는 트랜잭션을 대납 형식으로 조립해도 처리되는지 확인한다.',
     steps=['접근 목록을 붙인 트랜잭션을 보낸 이가 서명한다.', '대납자가 대납 형식으로 조립해 전송한다.', '접근 목록이 없는 대납 트랜잭션도 함께 보낸다.'],
     expected='두 트랜잭션 모두 블록에 포함되고 상태가 성공이다.',
     diff='세 클라이언트 모두 대납 형식에 접근 목록을 복사하는 경로가 있다.',
     deps=['계정'], sep='설정+기대값',
     spec=['T-2'], auto=[], pr196=None, note='StableNet과 WEMIX4.0 2차 변경 테스트에 같은 번호로 있다.'),
dict(id='CT-TX-011', area='TX', name='노드 키 저장소 경유 대납 서명',
     purpose='노드의 키 저장소로 대납 트랜잭션을 서명·전송하는 경로가 동작하는지 확인한다.',
     steps=['노드에 잠금 해제된 계정으로 대납 트랜잭션 전송을 요청한다.', '대납자 키로 서명할 때 형식이 맞지 않으면 거부되는지 확인한다.'],
     expected='정상 요청은 처리되고, 형식이 맞지 않는 서명 요청은 거부된다.',
     diff='세 클라이언트 모두 키 저장소가 대납 형식을 서명한다.',
     deps=['계정','RPC'], sep='설정+기대값',
     spec=['T-3'], auto=[], pr196=None, note='공개 RPC에는 잠금 해제 계정이 없어 소유한 네트워크에서만 가능.'),
dict(id='CT-TX-012', area='TX', name='계정별 nonce 순서 보장',
     purpose='한 계정에서 nonce 역순으로 보낸 트랜잭션이 오름차순으로 블록에 포함되는지 확인한다.',
     steps=['새 계정에 자금을 넣는다.', 'nonce 2, 1, 0 순서로 트랜잭션을 전송한다.', '계정 nonce가 3이 될 때까지 기다린다.'],
     expected='세 트랜잭션이 모두 포함되고 nonce가 3이다. 해시 중복이나 누락이 없다.',
     diff='',
     deps=['계정','수수료'], sep='설정',
     spec=['RT-A-2-04','TX-010'], auto=['nonce-ordering','out-of-order-nonces-mine'], pr196='P0', note=''),
dict(id='CT-TX-013', area='TX', name='같은 nonce 트랜잭션 교체',
     purpose='대기 중인 트랜잭션을 같은 nonce에 더 높은 수수료로 다시 보내면 새 것만 포함되는지 확인한다.',
     steps=['nonce 격차를 두어 대기 상태 트랜잭션을 만든다.', '같은 nonce로 수수료를 10% 넘게 올린 트랜잭션을 보낸다.', '격차를 채우는 트랜잭션을 보내 처리되게 한다.'],
     expected='나중 트랜잭션만 블록에 포함되고 처음 것은 영수증이 없다.',
     diff='교체에 필요한 인상 비율(기본 10%)은 노드 설정값이라 프로필로 둔다.',
     deps=['계정','수수료'], sep='설정+기대값',
     spec=['RT-A-2-09','TX-013'], auto=['replacement-tx','same-nonce-replacement'], pr196='P1', note=''),
dict(id='CT-TX-014', area='TX', name='미포함 트랜잭션의 이월과 교체',
     purpose='블록에 들어가지 못한 트랜잭션이 풀에 남아 다음 블록에 순서대로 들어가고, 교체하면 새 것만 들어가는지 확인한다.',
     steps=['블록에 다 들어가지 못할 만큼 트랜잭션을 보낸다.', '남은 트랜잭션이 풀에 있는지 확인한다.', '그중 하나를 수수료를 올려 교체한다.', '다음 블록들의 포함 순서를 확인한다.'],
     expected='남은 트랜잭션이 nonce 순서대로 포함된다. 교체한 nonce에는 새 트랜잭션만 들어간다.',
     diff='블록에 넘치게 만드는 방법(크기 한도, 가스 한도)이 체인마다 다르다.',
     deps=['계정','수수료'], sep='설정+기대값',
     spec=['N-008'], auto=[], pr196=None, note='PR196 신규 테스트. 관측 부분만 공통.'),
dict(id='CT-TX-015', area='TX', name='잔액 부족 트랜잭션 거부',
     purpose='잔액보다 큰 금액을 보내면 풀 진입 단계에서 거부되는지 확인한다.',
     steps=['잔액에 1을 더한 금액으로 송금한다.', '응답과 블록 진행을 확인한다.'],
     expected='거부된다. 보낸 계정의 잔액과 nonce는 그대로다. 블록은 계속 만들어진다.',
     diff='거부 문구의 앞부분(잔액 부족)은 같고 뒤에 붙는 설명이 다르다. 거부 이유까지 확인하려면 문구 앞부분으로 판정한다.',
     deps=['계정'], sep='설정+기대값',
     spec=['RT-A-2-06','TX-011'], auto=['insufficient-funds-rejected','wbft-insufficient-funds-rejected','wemix-insufficient-funds-rejected'], pr196='P1',
     note='세 체인용 자동 테스트가 이미 있다.'),
dict(id='CT-TX-016', area='TX', name='블록 가스 한도 초과 트랜잭션 거부',
     purpose='가스 한도를 블록 한도보다 크게 잡으면 거부되는지 확인한다.',
     steps=['최신 블록의 가스 한도를 조회한다.', '그보다 1 큰 가스 한도로 전송한다.', '응답을 확인한다.'],
     expected='거부된다.',
     diff='CT-TX-015와 같다.',
     deps=['수수료'], sep='설정+기대값',
     spec=['RT-A-2-07','TX-012'], auto=['gas-limit-exceeds-block-rejected','gaslimit-exceeded-rejected'], pr196='P1', note=''),
dict(id='CT-TX-017', area='TX', name='거부와 실행 실패의 상태 구분',
     purpose='풀에서 거부된 트랜잭션과 블록에 들어가 실행에 실패한 트랜잭션이 각각 올바른 상태로 남는지 확인한다.',
     steps=['거부될 트랜잭션(잔액 부족)과 실행에 실패할 트랜잭션(되돌림, 가스 소진)을 보낸다.', '풀, 블록, 영수증을 조회한다.'],
     expected='거부된 것은 풀과 블록에 없다. 실행에 실패한 것은 블록에 있고 영수증 상태가 실패다.',
     diff='',
     deps=['계정','컨트랙트'], sep='설정+기대값',
     spec=['N-009'], auto=[], pr196=None, note='PR196 신규 테스트. 관측 부분만 공통.'),
dict(id='CT-TX-018', area='TX', name='트랜잭션 풀 전파',
     purpose='한 노드에 보낸 트랜잭션이 다른 노드에서 처리 결과로 보이는지 확인한다.',
     steps=['노드 1에 송금 트랜잭션을 보낸다.', '노드 2에서 받는 계정 잔액을 조회한다.'],
     expected='노드 2에서도 잔액이 늘어 있다.',
     diff='',
     deps=['계정','토폴로지'], sep='설정',
     spec=[], auto=['basic-txpool-propagation'], pr196='P1', note=''),
dict(id='CT-TX-019', area='TX', name='부하 전송 중 블록 진행',
     purpose='블록마다 일정 비율의 가스를 쓰는 트랜잭션을 계속 보내도 블록이 진행되는지 확인한다.',
     steps=['블록 가스의 30%를 쓰는 트랜잭션을 15블록 동안 보낸다.', '블록이 계속 만들어지는지 확인한다.'],
     expected='블록이 멈추지 않는다.',
     diff='부하용 컨트랙트 코드는 최신 명령어를 쓰지 않아 세 체인에서 실행된다. 처리량 측정은 아니다.',
     deps=['계정','컨트랙트','프로세스'], sep='별도 구현',
     spec=[], auto=['stress-tx-flood'], pr196='P2', note=''),
dict(id='CT-TX-020', area='TX', name='테스트 계정 자금 지급',
     purpose='새 계정에 노드 계정으로 자금을 넣는 준비 절차가 동작하는지 확인한다.',
     steps=['새 계정을 만든다.', '노드 계정에서 정해진 금액을 보낸다.', '잔액을 조회한다.'],
     expected='잔액이 보낸 금액 이상이다.',
     diff='노드 계정 서명은 소유한 네트워크에서만 된다. 공개 RPC에서는 자금이 있는 운영 계정과 로컬 서명이 필요하다.',
     deps=['계정'], sep='설정',
     spec=[], auto=['stablenet-faucet-funds'], pr196='P2', note='다른 테스트의 준비 절차로도 쓰인다.'),
# ---------------------------------------------------------------- FEE
dict(id='CT-FEE-001', area='FEE', name='최소 팁 미달 거부',
     purpose='노드가 받는 최소 팁보다 낮은 팁으로 보내면 거부되는지 확인한다.',
     steps=['팁과 최대 수수료를 1로 정해 전송한다.', '응답을 확인한다.'],
     expected='거부된다.',
     diff='최소 팁의 출처가 다르다. WEMIX3.0은 거버넌스가 노드에 넣어 주는 값, WEMIX4.0은 노드 실행 설정값, StableNet은 거버넌스 컨트랙트가 정한 팁이다(블록 헤더에도 같은 값이 기록된다).',
     deps=['수수료'], sep='설정+기대값',
     spec=['RT-A-2-05a','TX-002'], auto=['dynamic-fee-below-basefee-rejected'], pr196='P1', note=''),
dict(id='CT-FEE-002', area='FEE', name='최소 가스비 경계값',
     purpose='최소 가스비보다 낮으면 거부되고, 같거나 높으면 받아들여지는지 형식별로 확인한다.',
     steps=['체인의 최소 가스비를 조회하거나 설정에서 읽는다.', '예전 형식, 접근 목록 형식, 동적 수수료 형식으로 각각 최소 미만·같음·초과 값을 보낸다.', '응답과 영수증을 확인한다.'],
     expected='같음과 초과는 성공한다. 미만은 StableNet에서 거부된다. WEMIX3.0과 WEMIX4.0에서는 거부되거나 블록에 포함되지 않은 채 남는다.',
     diff='최소 가스비 검사 방식이 다르다. StableNet은 최대 수수료가 최소 기본 수수료와 최소 팁의 합보다 낮으면 풀에서 거부한다. WEMIX3.0과 WEMIX4.0의 풀은 팁 하한만 검사하고 최대 수수료 하한은 검사하지 않아, 최대 수수료가 기본 수수료보다 낮은 트랜잭션은 풀에 들어간 뒤 포함되지 않은 채 남는다. 두 체인은 판정을 미포함으로 두거나 팁 하한 경계로 바꿔야 한다.',
     deps=['수수료'], sep='설정+기대값',
     spec=['TC-1-3-01','TC-1-3-02','TC-1-3-03','TC-1-3-04','TC-1-3-05','TC-1-3-06','TS-1-3-01','TS-1-3-02'],
     auto=['legacy-gasprice-below-min-rejected','accesslist-gasprice-below-min-rejected','feecap-below-min-rejected','feecap-above-min-accepted','feecap-exact-min-accepted'], pr196='P1', note=''),
dict(id='CT-FEE-003', area='FEE', name='사용률 높을 때 기본 수수료 증가',
     purpose='블록 사용률이 기준을 넘으면 다음 블록 기본 수수료가 오르는지 확인한다.',
     steps=['기본 수수료를 기록한다.', '기준을 넘는 사용률로 여러 블록 동안 부하를 준다.', '기본 수수료를 다시 조회한다.'],
     expected='기본 수수료가 올랐다.',
     diff='기준과 변화폭이 다르다. StableNet은 20% 초과 시 2% 인상, WEMIX4.0은 표준 계산, WEMIX3.0은 거버넌스 값이다.',
     deps=['수수료','계정','프로세스'], sep='설정+기대값',
     spec=['RT-C-03'], auto=['anzeon-basefee-increase'], pr196='P1', note=''),
dict(id='CT-FEE-004', area='FEE', name='사용률 보통일 때 기본 수수료 유지',
     purpose='블록 사용률이 유지 구간이면 기본 수수료가 변하지 않는지 확인한다.',
     steps=['기본 수수료를 기록한다.', '유지 구간의 사용률로 부하를 준다.', '기본 수수료를 다시 조회한다.'],
     expected='기본 수수료가 같다.',
     diff='유지 구간이 다르다. StableNet은 6~20%다. WEMIX4.0 표준 계산에는 유지 구간이 없어 목표 사용률에서만 유지된다.',
     deps=['수수료','계정','프로세스'], sep='설정+기대값',
     spec=['RT-C-04'], auto=['anzeon-basefee-stable'], pr196='P1', note=''),
dict(id='CT-FEE-005', area='FEE', name='사용률 낮을 때 기본 수수료 감소',
     purpose='부하가 끝나면 기본 수수료가 내려가는지 확인한다.',
     steps=['부하를 주어 기본 수수료를 올린다.', '부하를 멈추고 여러 블록을 기다린다.', '기본 수수료를 조회한다.'],
     expected='최고점보다 낮아졌다.',
     diff='CT-FEE-003과 같다.',
     deps=['수수료','계정','프로세스'], sep='설정+기대값',
     spec=['RT-C-05'], auto=['anzeon-basefee-decrease'], pr196='P1', note=''),
dict(id='CT-FEE-006', area='FEE', name='기본 수수료 하한',
     purpose='기본 수수료가 체인이 정한 하한 아래로 내려가지 않는지 확인한다.',
     steps=['부하가 없는 상태에서 기본 수수료를 조회한다.', '하한과 비교한다.'],
     expected='하한 이상이다.',
     diff='하한이 다르다. StableNet은 20,000 Gwei 상수, WEMIX3.0은 거버넌스 계산의 최솟값 1, WEMIX4.0은 0이다. 프로필 값과 비교한다.',
     deps=['수수료'], sep='설정+기대값',
     spec=['RT-C-06'], auto=['basefee-minimum'], pr196='P1', note='상한은 WEMIX4.0에 없어 부록(2체인)으로 뺐다.'),
dict(id='CT-FEE-007', area='FEE', name='실제 적용 가스 가격 기록',
     purpose='영수증에 실제 적용 가스 가격이 기록되고 사용 가스가 기본값 이상인지 확인한다.',
     steps=['송금을 보낸다.', '영수증의 실제 적용 가스 가격과 사용 가스를 조회한다.'],
     expected='가스 가격이 0보다 크고 사용 가스가 21000 이상이다.',
     diff='',
     deps=['계정','수수료'], sep='설정',
     spec=['RT-A-2-08'], auto=['effective-gas-price'], pr196='P1', note=''),
dict(id='CT-FEE-008', area='FEE', name='실제 적용 가스 가격 노드 간 일치',
     purpose='같은 트랜잭션의 실제 적용 가스 가격이 생성 노드와 종단 노드에서 같은지 확인한다.',
     steps=['생성 노드에 송금을 보내 영수증을 조회한다.', '종단 노드가 그 블록까지 동기화되기를 기다린다.', '종단 노드에서 같은 영수증을 조회해 비교한다.'],
     expected='두 노드의 값이 같다.',
     diff='',
     deps=['계정','토폴로지'], sep='설정',
     spec=['TC-4-6-02'], auto=['effective-gas-price-regular-bp-en'], pr196='P1',
     note='명세의 "헤더 팁으로 재계산" 부분은 StableNet 전용이라 제외하고 노드 간 일치만 가져왔다.'),
dict(id='CT-FEE-009', area='FEE', name='스냅 동기화 노드의 영수증 가스 가격 보존',
     purpose='스냅 동기화로 받은 영수증에 이미 가스 가격이 있으면 덮어쓰지 않는지 확인한다.',
     steps=['스냅 동기화 노드를 준비한다.', '동기화 전에 만들어진 트랜잭션의 영수증을 두 노드에서 조회한다.'],
     expected='가스 가격이 생성 노드 값과 같다.',
     diff='',
     deps=['토폴로지'], sep='설정+기대값',
     spec=['TC-4-6-03','TS-4-6'], auto=[], pr196=None, note='TS-4-6의 인증 계정 부분은 StableNet 전용.'),
dict(id='CT-FEE-010', area='FEE', name='권장 가스 가격 조회',
     purpose='권장 가스 가격이 기본 수수료와 팁의 합으로 나오는지 확인한다.',
     steps=['권장 가스 가격을 조회한다.', '최신 블록의 기본 수수료와 체인의 팁 출처 값을 조회한다.', '합과 비교한다.'],
     expected='권장 가격이 기본 수수료와 팁의 합이고 0보다 크다.',
     diff='계산식은 세 클라이언트가 같고 팁 출처만 다르다. StableNet은 블록 헤더의 팁, WEMIX3.0은 거버넌스 제안값, WEMIX4.0은 하드포크 전에는 고정값이고 하드포크 후에는 최근 블록 표본이다.',
     deps=['수수료','RPC'], sep='설정+기대값',
     spec=['RT-G-2-01','RPC-016'], auto=['gas-price-positive','gas-price-equals-basefee-plus-tip'], pr196='P2', note=''),
dict(id='CT-FEE-011', area='FEE', name='권장 팁 조회',
     purpose='권장 팁이 체인의 팁 출처 값과 같은지 확인한다.',
     steps=['권장 팁을 조회한다.', '체인의 팁 출처 값을 조회해 비교한다.'],
     expected='두 값이 같다.',
     diff='CT-FEE-010과 같다.',
     deps=['수수료','RPC'], sep='설정+기대값',
     spec=['RT-G-2-02'], auto=['max-priority-fee-equals-gastip'], pr196='P2', note=''),
dict(id='CT-FEE-012', area='FEE', name='수수료 이력 조회',
     purpose='최근 블록의 기본 수수료 이력이 형식에 맞게 나오는지 확인한다.',
     steps=['최근 16개 블록의 수수료 이력을 조회한다.', '시작 블록과 기본 수수료 배열을 확인한다.'],
     expected='시작 블록이 16진수이고 기본 수수료 배열이 있다.',
     diff='StableNet 명세의 "하한 이상" 조건은 StableNet 전용이다.',
     deps=['RPC'], sep='설정',
     spec=['RT-G-2-03','RPC-017'], auto=['fee-history-well-formed'], pr196='P2', note=''),
# ---------------------------------------------------------------- CONTRACT
dict(id='CT-CONTRACT-001', area='CONTRACT', name='컨트랙트 배포',
     purpose='컨트랙트를 배포하면 주소가 생기고 코드가 조회되는지 확인한다.',
     steps=['정해진 값을 돌려주는 작은 컨트랙트를 배포한다.', '영수증의 컨트랙트 주소로 코드를 조회한다.', '호출해 반환값을 확인한다.'],
     expected='코드가 비어 있지 않다. 반환값이 42다.',
     diff='배포할 코드가 세 체인의 EVM에서 모두 실행돼야 한다. WEMIX3.0은 최신 명령어(PUSH0)를 지원하지 않는다.',
     deps=['계정','컨트랙트'], sep='설정+기대값',
     spec=['RT-A-3-01','TX-005'], auto=['contract-roundtrip','wemix-tx-and-contract','wbft-tx-and-contract'], pr196='P1',
     note='PR196에서는 네 가지 형식으로 각각 배포한다.'),
dict(id='CT-CONTRACT-002', area='CONTRACT', name='상태 변경 함수 호출',
     purpose='저장값을 바꾸는 함수를 호출하면 바뀐 값이 조회되는지 확인한다.',
     steps=['저장값 컨트랙트를 배포한다.', '저장값을 바꾸는 트랜잭션을 보낸다.', '조회 함수로 값을 읽는다.'],
     expected='상태가 성공이고 읽은 값이 바꾼 값이다.',
     diff='CT-CONTRACT-001과 같다.',
     deps=['계정','컨트랙트'], sep='설정+기대값',
     spec=['RT-A-3-02','TX-005'], auto=['stablenet-register-contract'], pr196='P1', note='등록된 컨트랙트 호출 자동 테스트와 절차가 겹친다.'),
dict(id='CT-CONTRACT-003', area='CONTRACT', name='조회 함수 호출',
     purpose='트랜잭션 없이 조회 호출로 값을 읽을 수 있는지 확인한다.',
     steps=['배포된 컨트랙트의 조회 함수를 호출한다.'],
     expected='정확한 값이 돌아오고 상태는 바뀌지 않는다.',
     diff='CT-CONTRACT-001과 같다.',
     deps=['컨트랙트'], sep='설정+기대값',
     spec=['RT-A-3-03','TX-005'], auto=[], pr196='P2', note=''),
dict(id='CT-CONTRACT-004', area='CONTRACT', name='가스 추정',
     purpose='가스 추정값이 실제 사용 가스 이상인지 확인한다.',
     steps=['호출 데이터로 가스를 추정한다.', '추정값을 한도로 지정해 실제로 보낸다.'],
     expected='성공하고 사용 가스가 추정값 이하다.',
     diff='',
     deps=['컨트랙트'], sep='설정',
     spec=['RT-A-3-04'], auto=['estimate-gas'], pr196='P2', note=''),
dict(id='CT-CONTRACT-005', area='CONTRACT', name='조회 호출의 되돌림 오류',
     purpose='되돌리는 함수를 조회 호출하면 오류와 사유가 돌아오는지 확인한다.',
     steps=['되돌리는 함수가 있는 컨트랙트를 배포한다.', '그 함수를 조회 호출한다.'],
     expected='실행 되돌림 오류가 돌아온다.',
     diff='기존 자동 테스트의 컨트랙트 코드가 PUSH0을 써서 WEMIX3.0에서는 배포가 실패한다. 세 체인에서 실행되는 코드로 바꾼다.',
     deps=['컨트랙트'], sep='설정+기대값',
     spec=['RT-A-3-05'], auto=['eth-call-revert-returns-error'], pr196='P1', note=''),
dict(id='CT-CONTRACT-006', area='CONTRACT', name='되돌림 트랜잭션의 실패 상태',
     purpose='되돌리는 함수를 트랜잭션으로 실행하면 영수증 상태가 실패이고 상태 변경이 없는지 확인한다.',
     steps=['항상 되돌리는 컨트랙트를 배포한다.', '호출 트랜잭션을 보낸다.', '영수증 상태를 확인한다.'],
     expected='배포는 성공, 호출은 실패 상태다. 쓴 가스만 차감된다.',
     diff='',
     deps=['계정','컨트랙트'], sep='설정',
     spec=['RT-A-3-06','TX-017'], auto=['revert-tx-status-zero','wbft-revert-status-zero','wemix-revert-status-zero','stablenet-negative-tx-revert'], pr196='P1',
     note='세 체인용 자동 테스트가 이미 있다.'),
dict(id='CT-CONTRACT-007', area='CONTRACT', name='가스 소진 트랜잭션',
     purpose='가스 한도를 부족하게 주면 실패하고 가스를 전부 쓰는지 확인한다.',
     steps=['무한 반복 컨트랙트를 배포한다.', '가스 한도 50,000으로 호출한다.', '영수증을 확인한다.'],
     expected='실패 상태이고 사용 가스가 50,000이다.',
     diff='',
     deps=['계정','컨트랙트'], sep='설정',
     spec=['RT-A-3-07','TX-018'], auto=['out-of-gas-consumes-all'], pr196='P1', note=''),
# ---------------------------------------------------------------- RPC
dict(id='CT-RPC-001', area='RPC', name='최신 블록 번호 조회',
     purpose='블록 번호가 계속 늘어나는지 확인한다.',
     steps=['일정 간격으로 블록 번호를 여러 번 조회한다.'],
     expected='이전 값 이상으로 늘어난다.',
     diff='',
     deps=['RPC'], sep='설정',
     spec=['RT-A-4-01','RPC-001'], auto=['basic-rpc-health','remote-rpc-health'], pr196='P1', note=''),
dict(id='CT-RPC-002', area='RPC', name='블록 번호로 블록 조회',
     purpose='최신 블록을 번호로 조회하면 필수 필드가 있는지 확인한다.',
     steps=['최신 블록을 조회한다.', '번호, 해시, 트랜잭션 목록 필드를 확인한다.'],
     expected='번호와 해시가 16진수이고 트랜잭션 목록 필드가 있다.',
     diff='WEMIX4.0 명세는 합의 정보 포함까지 요구한다. 그 부분은 2체인이라 제외했다.',
     deps=['RPC'], sep='설정',
     spec=['RT-G-1-01','RPC-002'], auto=['block-transactions-field'], pr196='P1', note=''),
dict(id='CT-RPC-003', area='RPC', name='블록 해시로 블록 조회',
     purpose='해시로 조회한 블록이 번호로 조회한 블록과 같은지 확인한다.',
     steps=['최신 블록의 해시와 번호를 조회한다.', '해시로 다시 조회해 비교한다.'],
     expected='해시와 번호가 같다.',
     diff='',
     deps=['RPC'], sep='설정',
     spec=['RT-G-1-02','RPC-002'], auto=['block-by-hash-consistency'], pr196='P1', note=''),
dict(id='CT-RPC-004', area='RPC', name='해시로 트랜잭션 조회',
     purpose='포함된 트랜잭션을 해시로 조회하면 보낸 이, 받는 이, 블록 번호, 금액이 있는지 확인한다.',
     steps=['송금을 보낸다.', '해시로 트랜잭션을 조회한다.'],
     expected='보낸 이와 받는 이가 요청값과 같고 블록 번호와 금액이 있다.',
     diff='',
     deps=['계정','RPC'], sep='설정',
     spec=['RT-G-1-03'], auto=['transaction-by-hash-fields'], pr196='P1', note=''),
dict(id='CT-RPC-005', area='RPC', name='영수증 조회',
     purpose='영수증에 상태, 실제 적용 가스 가격, 로그가 있는지 확인한다.',
     steps=['송금을 보낸다.', '영수증을 조회한다.'],
     expected='상태가 성공이고 가스 가격과 로그 필드가 있다.',
     diff='',
     deps=['계정','RPC'], sep='설정',
     spec=['RT-G-1-04','RPC-007'], auto=['transaction-receipt-fields'], pr196='P1', note=''),
dict(id='CT-RPC-006', area='RPC', name='계정 nonce 조회',
     purpose='트랜잭션을 보내면 계정 nonce가 1 늘어나는지 확인한다.',
     steps=['nonce를 조회한다.', '송금을 보낸다.', 'nonce를 다시 조회한다.'],
     expected='1 늘었다.',
     diff='',
     deps=['계정','RPC'], sep='설정',
     spec=['RT-G-1-05','RPC-015'], auto=['transaction-count-increments'], pr196='P1', note=''),
dict(id='CT-RPC-007', area='RPC', name='잔액 조회',
     purpose='잔액이 있는 계정의 잔액이 정확히 조회되는지 확인한다.',
     steps=['알려진 계정의 잔액을 조회한다.', '송금 전후로 다시 조회한다.'],
     expected='0보다 크고 송금 후 변화가 반영된다.',
     diff='',
     deps=['계정','RPC'], sep='설정',
     spec=['RT-A-4-02','RPC-012'], auto=['genesis-balance','remote-balance-check'], pr196='P2', note=''),
dict(id='CT-RPC-008', area='RPC', name='체인 ID 조회',
     purpose='모든 노드가 제네시스에 설정한 체인 ID를 돌려주는지 확인한다.',
     steps=['각 노드에서 체인 ID를 조회한다.', '설정값과 비교한다.'],
     expected='모든 노드가 설정값과 같은 값을 돌려준다.',
     diff='WEMIX3.0과 WEMIX4.0의 코드 기본값이 같으므로 체인 ID만으로 어느 체인인지 판단하지 않는다.',
     deps=['ChainID','RPC'], sep='설정',
     spec=['RT-A-4-05','RPC-013'], auto=['chain-id','remote-chain-info'], pr196='P3',
     note='기존 자동 테스트는 0보다 큰지만 보므로 설정값 비교로 바꾼다.'),
dict(id='CT-RPC-009', area='RPC', name='이벤트 로그 조회',
     purpose='이벤트를 내는 컨트랙트를 실행한 뒤 조건에 맞는 로그가 조회되는지 확인한다.',
     steps=['이벤트를 내는 컨트랙트를 배포하고 호출한다.', '주소와 토픽으로 로그를 조회한다.'],
     expected='조건에 맞는 로그가 돌아오고 토픽이 예상값과 같다.',
     diff='',
     deps=['계정','컨트랙트','RPC'], sep='설정',
     spec=['RT-A-4-04','RPC-014'], auto=['logs-query-well-formed','contract-event-emitted'], pr196='P1', note=''),
dict(id='CT-RPC-010', area='RPC', name='서명된 트랜잭션 전송과 풀 조회',
     purpose='직접 서명한 트랜잭션을 보내면 해시가 돌아오고 포함 전에 풀에서 보이는지 확인한다.',
     steps=['로컬 키로 서명한 트랜잭션을 보낸다.', '포함 전에 풀 내용을 조회한다.', '포함 후 영수증을 조회한다.'],
     expected='해시가 돌아온다. 풀에서 보였다가 블록에 포함된다.',
     diff='풀 조회는 관리용 API라 공개 RPC에서는 닫혀 있을 수 있다.',
     deps=['계정','RPC'], sep='설정',
     spec=['RT-A-4-03'], auto=[], pr196='P1', note='자동 테스트 value-transfer는 전송 부분만 대응.'),
dict(id='CT-RPC-011', area='RPC', name='트랜잭션 풀 건수 조회',
     purpose='대기 건수와 보류 건수가 넣은 수와 맞는지 확인한다.',
     steps=['연속 nonce 트랜잭션과 nonce 격차가 있는 트랜잭션을 넣는다.', '풀 건수를 조회한다.'],
     expected='대기 건수와 보류 건수가 넣은 수와 같다.',
     diff='',
     deps=['계정','RPC'], sep='설정',
     spec=['RT-G-4-02','RPC-018'], auto=['txpool-status'], pr196='P2',
     note='기존 자동 테스트는 형식만 보므로 건수 대조로 바꾼다.'),
dict(id='CT-RPC-012', area='RPC', name='트랜잭션 풀 내용 조회',
     purpose='대기·보류 항목에 보낸 이, nonce, 가스 가격이 들어 있는지 확인한다.',
     steps=['CT-RPC-011과 같은 상태를 만든다.', '풀 내용을 조회한다.'],
     expected='대기 항목에 연속 nonce, 보류 항목에 격차 nonce 트랜잭션이 상세 필드와 함께 있다.',
     diff='',
     deps=['계정','RPC'], sep='설정',
     spec=['RT-G-4-03','RPC-018'], auto=['txpool-content-well-formed'], pr196='P2', note=''),
dict(id='CT-RPC-013', area='RPC', name='새 블록 구독',
     purpose='웹소켓으로 새 블록 헤더를 실시간으로 받는지 확인한다.',
     steps=['웹소켓으로 새 블록 구독을 건다.', '블록이 만들어질 때마다 헤더를 받는지 본다.'],
     expected='연속 헤더를 받고 번호가 늘어난다.',
     diff='',
     deps=['RPC'], sep='설정',
     spec=['RT-A-4-06','RPC-020'], auto=['ws-subscribe-new-heads'], pr196='P2', note='웹소켓 주소가 프로필에 있어야 한다.'),
dict(id='CT-RPC-014', area='RPC', name='이벤트 로그 구독',
     purpose='웹소켓으로 특정 주소의 이벤트를 실시간으로 받는지 확인한다.',
     steps=['이벤트 컨트랙트를 배포한다.', '그 주소로 로그 구독을 건다.', '이벤트를 내는 트랜잭션을 보낸다.'],
     expected='이벤트가 바로 수신된다.',
     diff='',
     deps=['계정','컨트랙트','RPC'], sep='설정',
     spec=['RT-A-4-07','RPC-021'], auto=['ws-subscribe-logs'], pr196='P2', note=''),
dict(id='CT-RPC-015', area='RPC', name='노드 지표 조회',
     purpose='노드가 내놓는 지표에서 최신 블록 높이를 읽을 수 있는지 확인한다.',
     steps=['지표 기능을 켜고 노드를 띄운다.', '최신 블록 높이 지표를 읽는다.'],
     expected='값이 1 이상이다.',
     diff='지표 기능을 켜는 옵션은 세 클라이언트가 같다.',
     deps=['RPC','토폴로지'], sep='설정',
     spec=[], auto=['stablenet-metric-head-block'], pr196=None, note='공개 RPC에는 지표 주소가 없을 수 있다.'),
# ---------------------------------------------------------------- FAULT
dict(id='CT-FAULT-001', area='FAULT', name='생성 노드 1대 중단과 재시작',
     purpose='생성 노드 하나를 멈춰도 블록이 계속 만들어지고, 다시 띄우면 따라잡는지 확인한다.',
     steps=['블록 높이가 3 이상이 되기를 기다린다.', '생성 노드 하나를 멈춘다.', '다른 노드에서 블록이 계속 늘어나는지 본다.', '멈춘 노드를 다시 띄우고 같은 높이의 해시와 상태 루트를 비교한다.'],
     expected='나머지 노드가 블록을 계속 만든다. 복구 노드의 해시와 상태 루트가 기준 노드와 같다.',
     diff='허용되는 장애 수가 다르다. WEMIX4.0과 StableNet은 검증자 3분의 2 이상이 살아 있어야 한다. WEMIX3.0은 생성 노드가 함께 운영하는 etcd 클러스터가 유지돼야 하며 과반이 살아 있어야 한다.',
     deps=['토폴로지','프로세스'], sep='별도 구현',
     spec=['RT-A-1-04','NODE-005'], auto=['fault-node-crash','wemix-node-crash','wbft-node-crash','sample-lifecycle-node-restart'], pr196='P1',
     note='소유한 네트워크에서만 가능.'),
dict(id='CT-FAULT-002', area='FAULT', name='중단 노드 복구 후 동기화',
     purpose='오래 멈춘 노드가 다시 뜬 뒤 최신 블록까지 동기화하는지 확인한다.',
     steps=['노드 하나를 멈춘다.', '나머지가 블록을 여러 개 만들 때까지 기다린다.', '다시 띄우고 최신 해시가 일치할 때까지 기다린다.'],
     expected='최신 블록 해시가 모든 노드에서 같다.',
     diff='CT-FAULT-001과 같다.',
     deps=['토폴로지','프로세스'], sep='별도 구현',
     spec=[], auto=['fault-node-recover'], pr196='P1', note=''),
dict(id='CT-FAULT-003', area='FAULT', name='생성 노드 2대 중단 시 합의 중단과 복구',
     purpose='4대 중 2대를 멈추면 블록 생성이 멈추고, 1대를 되살리면 재개되는지 확인한다.',
     steps=['생성 노드 2대를 멈춘다.', '블록이 멈추는지 확인한다.', '1대를 다시 띄우고 블록이 재개되는지 본다.'],
     expected='2대 중단 시 멈추고 1대 복구 시 재개된다.',
     diff='멈추는 조건이 다르다. WEMIX4.0과 StableNet은 4대 중 3대가 필요하다. WEMIX3.0은 etcd 과반 규칙이라 같은 수에서 멈추는지 따로 판정해야 한다.',
     deps=['토폴로지','프로세스'], sep='별도 구현',
     spec=[], auto=['fault-two-down'], pr196='P1', note=''),
dict(id='CT-FAULT-004', area='FAULT', name='네트워크 분리와 복구',
     purpose='노드를 두 무리로 갈랐다가 다시 이으면 체인이 하나로 합쳐지는지 확인한다.',
     steps=['피어 연결을 끊어 2대씩 두 무리로 가른다.', '피어 수가 줄었는지 확인한다.', '다시 잇고 최신 해시가 같아질 때까지 기다린다.'],
     expected='분리 중 피어 수가 2 이하다. 복구 후 최신 해시가 같다.',
     diff='피어를 끊는 관리 API가 열려 있어야 한다. 자동 재연결이 켜진 네트워크에서는 분리가 유지되지 않을 수 있다.',
     deps=['토폴로지','프로세스','RPC'], sep='별도 구현',
     spec=[], auto=['fault-network-partition'], pr196='P1', note=''),
dict(id='CT-FAULT-005', area='FAULT', name='허브형 연결에서 합의와 전파',
     purpose='한 노드만 나머지와 연결된 형태에서도 블록과 트랜잭션이 전파되는지 확인한다.',
     steps=['허브 노드 하나만 남기고 나머지 노드 사이 연결을 끊는다.', '허브에 송금을 보낸다.', '블록 진행과 잔액을 확인하고 연결을 복구한다.'],
     expected='블록이 진행되고 송금이 처리된다. 복구 후 해시가 같다.',
     diff='CT-FAULT-004와 같다.',
     deps=['계정','토폴로지','프로세스','RPC'], sep='별도 구현',
     spec=[], auto=['fault-p2p-topology'], pr196='P1', note=''),
dict(id='CT-FAULT-006', area='FAULT', name='생산 노드 중단 시 대기 트랜잭션 처리',
     purpose='트랜잭션을 받은 노드가 멈춰도 다른 노드가 그 트랜잭션을 처리하는지 확인한다.',
     steps=['노드 1에 송금을 보낸다.', '노드 1을 멈춘다.', '노드 2에서 블록 진행과 풀 대기 건수를 확인한다.'],
     expected='블록이 진행되고 대기 건수가 0이 된다.',
     diff='CT-FAULT-001과 같다.',
     deps=['계정','토폴로지','프로세스','RPC'], sep='별도 구현',
     spec=[], auto=['fault-txpool-leader-change'], pr196='P1', note=''),
]

AREA_NAME = {'NODE': '노드·동기화·네트워크', 'TX': '트랜잭션 전송·거부', 'FEE': '수수료·가스 정책',
             'CONTRACT': '컨트랙트 실행', 'RPC': '조회·구독 API', 'FAULT': '장애·복구'}
