#!/usr/bin/env bash
# gen-env.sh — generate the local docker fleet that poses as remote servers.
#
# Writes everything into build/ (gitignored): the compose file, the v2
# server set (real bridge addresses — the file has the same shape a
# production server set has), and localmap.yaml (the address translation
# `--docker` applies; see docs/dev/docker-remote-design.md).
#
# Access mirrors the real fleet: a user id + password (dev-only value, on
# loopback-published containers) and sudo that asks for that password.
# There is no key path — the harness has to prove the password flows.
#
# Nothing in build/ is handwritten. To change the fleet, change the knobs
# below and run this again.
set -euo pipefail

cd "$(dirname "$0")"

# ---- knobs ---------------------------------------------------------------
SERVERS="${SERVERS:-15}"          # server1..serverN (server15 is meant for pn)
SLOTS="${SLOTS:-4}"               # port slots per server (nodes one host may hold)
SUBNET_PREFIX="172.30.0"          # server i lives at .$((ADDR_OFFSET+i))
ADDR_OFFSET=10
SSH_PUB_BASE=2200                 # server i's sshd published at 127.0.0.1:$((base+i))
RPC_PUB_BASE=18600                # slot s of server i published at $((base + 100*s + i))
RPC_PORT=8600                     # the rpc band base (slot s listens on base + 10*s)
RPC_STEP=10
IMAGE="chainbench-server:ubuntu24"
DATA_ROOT="/data/chainbench"
ACCOUNTS_ENV=accounts.env         # dev accounts injected at container start
# --------------------------------------------------------------------------

BUILD=build
mkdir -p "$BUILD"

die() { echo "gen-env: $*" >&2; exit 1; }

# Dev accounts (name:uid pairs + shared password) live in a gitignored file so
# nothing is hardcoded here or in the Dockerfile; setup-accounts.sh reads the
# same file inside each container at start. The copy is deliberate — silently
# seeding the sample would hand sudo-capable accounts the tracked placeholder
# password, so refuse to run until a real file with a real password exists.
[ -f "$ACCOUNTS_ENV" ] || die "$ACCOUNTS_ENV not found. Run:
  cp ${ACCOUNTS_ENV}.sample $ACCOUNTS_ENV   # then set a real password in it"
. "./$ACCOUNTS_ENV"
[ -n "${DEV_ACCOUNTS:-}" ] || die "DEV_ACCOUNTS is empty in $ACCOUNTS_ENV"
case "${DEV_ACCOUNTS_PASSWORD:-}" in
    '' | change-me) die "set a real DEV_ACCOUNTS_PASSWORD in $ACCOUNTS_ENV (not the sample placeholder)" ;;
esac

# The harness login is the FIRST account in accounts.env — the real fleet is
# reached with a provisioned dev account, not a baked-in image user, so the
# docker fleet mirrors that. setup-accounts.sh is what creates the accounts,
# hence no override knob: an inventory user it does not create is a dead login.
first_account=${DEV_ACCOUNTS%% *}
case $first_account in
    ?*:*) ;;
    *) die "first DEV_ACCOUNTS entry '$first_account' is not name:uid" ;;
esac
SSH_USER=${first_account%%:*}
SSH_PASSWORD=$DEV_ACCOUNTS_PASSWORD

# Single-quote a scalar for YAML: '' escapes an embedded quote. Without this a
# password containing ': ', ' #', or a leading indicator corrupts the inventory.
yaml_sq() { printf "'%s'" "$(printf '%s' "$1" | sed "s/'/''/g")"; }

addr() { echo "${SUBNET_PREFIX}.$((ADDR_OFFSET + $1))"; }

# ---- docker-compose.yml --------------------------------------------------
{
    cat <<EOF
# generated by gen-env.sh — do not edit; rerun the script instead.
name: chainbench-servers
networks:
  chainbench:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET_PREFIX}.0/24
services:
EOF
    for i in $(seq 1 "$SERVERS"); do
        cat <<EOF
  server${i}:
    image: ${IMAGE}
    container_name: chainbench-server${i}
    hostname: server${i}
    networks:
      chainbench:
        ipv4_address: $(addr "$i")
    ports:
      # published on loopback only: nothing outside this machine can reach them
      - "127.0.0.1:$((SSH_PUB_BASE + i)):22"
EOF
        for s in $(seq 0 $((SLOTS - 1))); do
            echo "      - \"127.0.0.1:$((RPC_PUB_BASE + 100 * s + i)):$((RPC_PORT + RPC_STEP * s))\""
        done
        cat <<EOF
    volumes:
      # dev accounts: created at start by setup-accounts.sh from accounts.env
      - ../${ACCOUNTS_ENV}:/etc/chainbench/accounts.env:ro
      - ../setup-accounts.sh:/usr/local/lib/chainbench/setup-accounts.sh:ro
    command:
      - /bin/sh
      - -c
      - >-
        sh /usr/local/lib/chainbench/setup-accounts.sh
        && mkdir -p ${DATA_ROOT}
        && chown ${SSH_USER}:${SSH_USER} ${DATA_ROOT}
        && exec /usr/sbin/sshd -D -e
EOF
    done
} > "$BUILD/docker-compose.yml"

# ---- server-set.yaml (v2, REAL addresses) --------------------------------
{
    cat <<EOF
# generated by gen-env.sh — the same shape a production server set has.
# Addresses are the containers' own; the harness reaches them only through
# localmap.yaml when --docker is set.
version: 2

pool:
  hosts:
EOF
    for i in $(seq 1 "$SERVERS"); do
        echo "    - { name: server${i}, addr: $(addr "$i") }"
    done
    cat <<EOF
  slots: ${SLOTS}

ssh:
  user: $(yaml_sq "$SSH_USER")
  port: 22
  # Dev-only credential for loopback-published containers; a production
  # server set would reference a password_file instead of an inline value.
  password: $(yaml_sq "$SSH_PASSWORD")
  sudo: true

dataRoot: ${DATA_ROOT}
EOF
} > "$BUILD/server-set.yaml"

# ---- localmap.yaml -------------------------------------------------------
{
    cat <<EOF
# generated by gen-env.sh — applied only under --docker.
# Maps each server's real address onto the loopback-published ports, because
# macOS cannot route across the Rancher VM boundary to a container's address.
hosts:
EOF
    for i in $(seq 1 "$SERVERS"); do
        ports="22: $((SSH_PUB_BASE + i))"
        for s in $(seq 0 $((SLOTS - 1))); do
            ports="${ports}, $((RPC_PORT + RPC_STEP * s)): $((RPC_PUB_BASE + 100 * s + i))"
        done
        cat <<EOF
  $(addr "$i"):
    host: 127.0.0.1
    ports: { ${ports} }
EOF
    done
} > "$BUILD/localmap.yaml"

echo "generated: $BUILD/{docker-compose.yml, server-set.yaml, localmap.yaml}"
echo
echo "next:"
echo "  docker build -t ${IMAGE} ."
echo "  docker compose -f $BUILD/docker-compose.yml up -d"
echo "  ssh -p $((SSH_PUB_BASE + 1)) ${SSH_USER}@127.0.0.1 hostname   # password: ${SSH_PASSWORD} -> server1"
