#!/usr/bin/env bash
# gen-env.sh — generate the local docker fleet that poses as remote servers.
#
# Writes everything into build/ (gitignored): an ssh keypair, the compose
# file, the v2 server inventory (real bridge addresses — the file has the
# same shape a production inventory has), and localmap.yaml (the address
# translation `--docker` applies; see docs/dev/docker-remote-design.md).
#
# Nothing in build/ is handwritten. To change the fleet, change the knobs
# below and run this again.
set -euo pipefail

cd "$(dirname "$0")"

# ---- knobs ---------------------------------------------------------------
SERVERS="${SERVERS:-15}"          # server1..serverN (server15 is meant for pn)
SLOTS="${SLOTS:-4}"               # port slots per server (nodes one host may hold)
SUBNET_PREFIX="172.30.0"          # server i lives at .$((ADDR_OFFSET+i))
ADDR_OFFSET=10
SSH_PUB_BASE=2200                 # server i's sshd published at 127.0.0.1:$((base+i))
RPC_PUB_BASE=18600                # slot s of server i published at $((base + 100*s + i))
RPC_PORT=8600                     # the rpc band base (slot s listens on base + 10*s)
RPC_STEP=10
IMAGE="chainbench-server:ubuntu24"
DATA_ROOT="/data/chainbench"
# --------------------------------------------------------------------------

BUILD=build
mkdir -p "$BUILD/ssh"

# The dev-only keypair. Kept if it exists so containers keep accepting it.
if [ ! -f "$BUILD/ssh/id_ed25519" ]; then
    ssh-keygen -q -t ed25519 -N "" -C chainbench-docker -f "$BUILD/ssh/id_ed25519"
fi
cp "$BUILD/ssh/id_ed25519.pub" "$BUILD/ssh/authorized_keys"

addr() { echo "${SUBNET_PREFIX}.$((ADDR_OFFSET + $1))"; }

# ---- docker-compose.yml --------------------------------------------------
{
    cat <<EOF
# generated by gen-env.sh — do not edit; rerun the script instead.
name: chainbench-servers
networks:
  chainbench:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET_PREFIX}.0/24
services:
EOF
    for i in $(seq 1 "$SERVERS"); do
        cat <<EOF
  server${i}:
    image: ${IMAGE}
    container_name: chainbench-server${i}
    hostname: server${i}
    networks:
      chainbench:
        ipv4_address: $(addr "$i")
    ports:
      # published on loopback only: nothing outside this machine can reach them
      - "127.0.0.1:$((SSH_PUB_BASE + i)):22"
EOF
        for s in $(seq 0 $((SLOTS - 1))); do
            echo "      - \"127.0.0.1:$((RPC_PUB_BASE + 100 * s + i)):$((RPC_PORT + RPC_STEP * s))\""
        done
        cat <<EOF
    volumes:
      - ./ssh/authorized_keys:/etc/chainbench/authorized_keys:ro
    command:
      - /bin/sh
      - -c
      - >-
        mkdir -p /root/.ssh ${DATA_ROOT}
        && install -m 600 /etc/chainbench/authorized_keys /root/.ssh/authorized_keys
        && exec /usr/sbin/sshd -D -e
EOF
    done
} > "$BUILD/docker-compose.yml"

# ---- remote-server-config.yaml (inventory v2, REAL addresses) ------------
KEY_ABS="$(cd "$BUILD/ssh" && pwd)/id_ed25519"
{
    cat <<EOF
# generated by gen-env.sh — the same shape a production inventory has.
# Addresses are the containers' own; the harness reaches them only through
# localmap.yaml when --docker is set.
version: 2

pool:
  hosts:
EOF
    for i in $(seq 1 "$SERVERS"); do
        echo "    - { name: server${i}, addr: $(addr "$i") }"
    done
    cat <<EOF
  slots: ${SLOTS}

ssh:
  user: root
  port: 22
  key_file: ${KEY_ABS}
  sudo: true

dataRoot: ${DATA_ROOT}
EOF
} > "$BUILD/remote-server-config.yaml"

# ---- localmap.yaml -------------------------------------------------------
{
    cat <<EOF
# generated by gen-env.sh — applied only under --docker.
# Maps each server's real address onto the loopback-published ports, because
# macOS cannot route across the Rancher VM boundary to a container's address.
hosts:
EOF
    for i in $(seq 1 "$SERVERS"); do
        ports="22: $((SSH_PUB_BASE + i))"
        for s in $(seq 0 $((SLOTS - 1))); do
            ports="${ports}, $((RPC_PORT + RPC_STEP * s)): $((RPC_PUB_BASE + 100 * s + i))"
        done
        cat <<EOF
  $(addr "$i"):
    host: 127.0.0.1
    ports: { ${ports} }
EOF
    done
} > "$BUILD/localmap.yaml"

echo "generated: $BUILD/{docker-compose.yml, remote-server-config.yaml, localmap.yaml, ssh/}"
echo
echo "next:"
echo "  docker build -t ${IMAGE} ."
echo "  docker compose -f $BUILD/docker-compose.yml up -d"
echo "  ssh -i $BUILD/ssh/id_ed25519 -p $((SSH_PUB_BASE + 1)) root@127.0.0.1 hostname   # -> server1"
