package lifecycle

// The name of every declared state, for [Status.String].
//
// Written out rather than derived: Go has no way to ask a constant for its own
// name, and a state printing as a number is a state a reader has to look up by
// hand. names_test.go holds this list to the declarations, in both directions.

// names is what each declared state is called, for messages and for the checks
// that walk the table. A state missing from here is one the table can still
// reach, so [TestEveryStateIsNamed] holds the two together.
var names = map[Status]string{
	ChainOpenWorkspace:                    "ChainOpenWorkspace",
	ChainOpenWorkspaceFailNoChain:         "ChainOpenWorkspaceFailNoChain",
	ChainBuildNodeTable:                   "ChainBuildNodeTable",
	ChainBuildNodeTableFailTwoLayouts:     "ChainBuildNodeTableFailTwoLayouts",
	ChainBuildNodeTableFailSetContended:   "ChainBuildNodeTableFailSetContended",
	ChainEnsureKeys:                       "ChainEnsureKeys",
	ChainEnsureKeysFromPreset:             "ChainEnsureKeysFromPreset",
	ChainEnsureKeysGenerated:              "ChainEnsureKeysGenerated",
	ChainEnsureKeysFromBlueprint:          "ChainEnsureKeysFromBlueprint",
	ChainEnsureKeysFailUnknownSource:      "ChainEnsureKeysFailUnknownSource",
	ChainEnsureKeysFailCountMismatch:      "ChainEnsureKeysFailCountMismatch",
	ChainEnsureKeysFailKeyNotLocal:        "ChainEnsureKeysFailKeyNotLocal",
	ChainEnsureKeysFailKeyUnreadable:      "ChainEnsureKeysFailKeyUnreadable",
	ChainBuildGenesis:                     "ChainBuildGenesis",
	ChainBuildGenesisFromTemplate:         "ChainBuildGenesisFromTemplate",
	ChainBuildGenesisFromExisting:         "ChainBuildGenesisFromExisting",
	ChainBuildGenesisForkApplied:          "ChainBuildGenesisForkApplied",
	ChainBuildGenesisVariantsWritten:      "ChainBuildGenesisVariantsWritten",
	ChainBuildGenesisFailExistingInvalid:  "ChainBuildGenesisFailExistingInvalid",
	ChainBuildGenesisFailExistingForeign:  "ChainBuildGenesisFailExistingForeign",
	ChainBuildGenesisFailForkUnresolved:   "ChainBuildGenesisFailForkUnresolved",
	ChainBuildGenesisFailDeclUnused:       "ChainBuildGenesisFailDeclUnused",
	ChainBuildGenesisFailTargetUnable:     "ChainBuildGenesisFailTargetUnable",
	ChainBuildNodeConfig:                  "ChainBuildNodeConfig",
	ChainBuildNodeConfigFailBadOverride:   "ChainBuildNodeConfigFailBadOverride",
	ChainBuildNodeConfigFailReadback:      "ChainBuildNodeConfigFailReadback",
	ChainBuildNodeConfigFailPinUnreadable: "ChainBuildNodeConfigFailPinUnreadable",
	ChainBuildNodeCommand:                 "ChainBuildNodeCommand",
	ChainBuildNodeCommandFailBadOption:    "ChainBuildNodeCommandFailBadOption",
	ChainBuildNodeCommandFailSplitNetwork: "ChainBuildNodeCommandFailSplitNetwork",
	ChainDeployNodes:                      "ChainDeployNodes",
	ChainDeployNodesVerifiedLocal:         "ChainDeployNodesVerifiedLocal",
	ChainDeployNodesShippedRemote:         "ChainDeployNodesShippedRemote",
	ChainDeployNodesFailInputMissing:      "ChainDeployNodesFailInputMissing",
	ChainDeployNodesFailInputForeign:      "ChainDeployNodesFailInputForeign",
	ChainInitNodes:                        "ChainInitNodes",
	ChainInitNodesFailTargetUnable:        "ChainInitNodesFailTargetUnable",
	ChainInitNodesFailGenesisUnreadable:   "ChainInitNodesFailGenesisUnreadable",
	ChainInitNodesFailDatadir:             "ChainInitNodesFailDatadir",
	ChainLaunchNodes:                      "ChainLaunchNodes",
	ChainLaunchNodesPhaseLaunching:        "ChainLaunchNodesPhaseLaunching",
	ChainLaunchNodesPhaseActions:          "ChainLaunchNodesPhaseActions",
	ChainLaunchNodesPhaseDone:             "ChainLaunchNodesPhaseDone",
	ChainLaunchNodesFailNoBinary:          "ChainLaunchNodesFailNoBinary",
	ChainLaunchNodesFailPortBusy:          "ChainLaunchNodesFailPortBusy",
	ChainLaunchNodesFailOccupied:          "ChainLaunchNodesFailOccupied",
	ChainLaunchNodesFailNoKeystore:        "ChainLaunchNodesFailNoKeystore",
	ChainLaunchNodesFailPhaseEmpty:        "ChainLaunchNodesFailPhaseEmpty",
	ChainVerify:                           "ChainVerify",
	ChainVerifyProducing:                  "ChainVerifyProducing",
	ChainVerifyHaltedAsDeclared:           "ChainVerifyHaltedAsDeclared",
	ChainVerifyFailPlanMismatch:           "ChainVerifyFailPlanMismatch",
	ChainVerifyFailNotProducing:           "ChainVerifyFailNotProducing",
	ChainReady:                            "ChainReady",
	AdoptChain:                            "AdoptChain",
	AdoptChainByRPC:                       "AdoptChainByRPC",
	AdoptChainByWorkspace:                 "AdoptChainByWorkspace",
	AdoptChainByDeclaration:               "AdoptChainByDeclaration",
	AdoptChainFailUnreachable:             "AdoptChainFailUnreachable",
	AdoptChainFailWrongChain:              "AdoptChainFailWrongChain",
	CompareChain:                          "CompareChain",
	CompareChainSame:                      "CompareChainSame",
	CompareChainNodesDiffer:               "CompareChainNodesDiffer",
	CompareChainNetworkDiffers:            "CompareChainNetworkDiffers",
	CompareChainNothingComposed:           "CompareChainNothingComposed",
	CompareChainFailUnreadable:            "CompareChainFailUnreadable",
	ReconcileChain:                        "ReconcileChain",
	ReconcileChainAllKept:                 "ReconcileChainAllKept",
	ReconcileChainSomeRedone:              "ReconcileChainSomeRedone",
	ReconcileChainFailSharedInputChanged:  "ReconcileChainFailSharedInputChanged",
	ReconcileChainFailUnreadable:          "ReconcileChainFailUnreadable",
	FailRecordFormat:                      "FailRecordFormat",
	FailRecordSave:                        "FailRecordSave",
	FailWorkspaceConfig:                   "FailWorkspaceConfig",
	FailLoop:                              "FailLoop",
	FailNoHandler:                         "FailNoHandler",
	ChainStopped:                          "ChainStopped",
	ChainRemoved:                          "ChainRemoved",
	ChainOpStopNodes:                      "ChainOpStopNodes",
	ChainOpStopNodesFailSomeStillUp:       "ChainOpStopNodesFailSomeStillUp",
	ChainOpStartNodes:                     "ChainOpStartNodes",
	ChainOpReplaceNode:                    "ChainOpReplaceNode",
	ChainOpReplaceNodeFailNothingAsked:    "ChainOpReplaceNodeFailNothingAsked",
	ChainOpCrossFork:                      "ChainOpCrossFork",
	ChainOpCrossForkBeforeFork:            "ChainOpCrossForkBeforeFork",
	ChainOpCrossForkHandingOver:           "ChainOpCrossForkHandingOver",
	ChainOpCrossForkCrossed:               "ChainOpCrossForkCrossed",
	ChainOpCrossForkFailNoFork:            "ChainOpCrossForkFailNoFork",
	ChainOpCrossForkFailHeadUnreadable:    "ChainOpCrossForkFailHeadUnreadable",
	ChainOpCrossForkFailAlreadyPast:       "ChainOpCrossForkFailAlreadyPast",
	ChainOpCrossForkFailNobodyCameBack:    "ChainOpCrossForkFailNobodyCameBack",
	ChainOpRemoveNodes:                    "ChainOpRemoveNodes",
	ChainOpHardfork:                       "ChainOpHardfork",
	ChainOpFailPrecondition:               "ChainOpFailPrecondition",
	ChainOpFailNoSuchNode:                 "ChainOpFailNoSuchNode",
	FailStageUnclassified:                 "FailStageUnclassified",

	TestReadDeclaration:                 "TestReadDeclaration",
	TestReadDeclarationFailUnreadable:   "TestReadDeclarationFailUnreadable",
	TestReadDeclarationFailMalformed:    "TestReadDeclarationFailMalformed",
	TestReadDeclarationFailIncomplete:   "TestReadDeclarationFailIncomplete",
	TestReadDeclarationFailUnknownName:  "TestReadDeclarationFailUnknownName",
	TestReadDeclarationFailContradicted: "TestReadDeclarationFailContradicted",
	TestOpenSession:                     "TestOpenSession",
	TestOpenSessionFailNoRoot:           "TestOpenSessionFailNoRoot",
	TestReachNetwork:                    "TestReachNetwork",
	TestReachNetworkFailCompose:         "TestReachNetworkFailCompose",
	TestReachNetworkFailNotThePlan:      "TestReachNetworkFailNotThePlan",
	TestReachNetworkFailUnreachable:     "TestReachNetworkFailUnreachable",
	TestPrepare:                         "TestPrepare",
	TestPrepareFailFork:                 "TestPrepareFailFork",
	TestPrepareFailHeight:               "TestPrepareFailHeight",
	TestPrepareFailAccount:              "TestPrepareFailAccount",
	TestRunCases:                        "TestRunCases",
	TestRunCasesFailCannotProceed:       "TestRunCasesFailCannotProceed",
	TestCollect:                         "TestCollect",
	TestCollectFailEvidence:             "TestCollectFailEvidence",
	TestFinished:                        "TestFinished",
}
