package genesis

import (
	"context"
	"fmt"

	"github.com/0xmhha/chainbench/internal/core/filestore"
	"github.com/0xmhha/chainbench/internal/core/keyring/store"
	"github.com/0xmhha/chainbench/internal/core/node"
	"github.com/0xmhha/chainbench/internal/core/registry"
)

// CommandRunner runs a binary with args and returns its combined output. It is
// the seam that lets a family whose genesis its own binary writes run that
// binary somewhere other than this process — on the target host, when the
// network is composed remotely. Its signature matches the poa runner exactly,
// so a family assigns it to its own runner field without conversion.
type CommandRunner func(ctx context.Context, name string, args ...string) ([]byte, error)

// Source produces a network's genesis bytes for a chain plugin, sized to
// the active validator count. It is a boundary so BuildEnv does not depend on where
// the validator set and RLP extra-data come from: a baked preset today, and a
// live key deriver (once a Go extra-data encoder exists) later.
type Source interface {
	// Genesis builds the genesis artifacts for plugin from the network being
	// composed.
	Genesis(ctx context.Context, plugin registry.ChainPlugin, req Request) (Artifacts, error)
}

// Request is the network a genesis is being built for.
//
// Validators alone was enough while every family kept its validator set inside
// the  A wemix genesis does not: its governance config names the
// producer by address, public key, host and p2p port, so the source has to know
// where the network will actually run. Passing the placement is what lets the
// family that needs it read it, and the one that does not ignore it.
type Request struct {
	// Validators is how many of the key set's entries produce blocks; <=0 is
	// the whole set.
	Validators int
	// Nodes is the resolved placement, or nil when a caller has none (a
	// fixed-port setup path). A family that needs an address errors on nil
	// rather than inventing one.
	Nodes *node.Map
}

// Artifacts is what a genesis step produces. For most families that is
// one file; for wemix it is not.
//
// A wemix genesis is generated by the binary from a governance config, and that
// same config is then an input to deploy-governance during the bring-up. The
// step's by-product has to reach a later step, so the source returns it here
// instead of the caller reconstructing it — reconstructing is how two callers
// come to disagree about what the network was configured with.
type Artifacts struct {
	// Genesis is the json bytes.
	Genesis []byte
	// Extra are further files the family needs on the target, keyed by the
	// name they take there ("wemix-config.json"). Families that need none
	// leave it nil.
	Extra map[string][]byte
}

// PresetSource builds genesis from a baked preset key set. The preset is
// the only source of a wbft-family network's RLP extra-data: the consensus
// family substitutes the extra-data into its template but does not compute it,
// so a freshly generated random key set cannot seed a valid wbft genesis on its
// own. Node identity/account keys (nodekey, unlock) come from the key registry;
// the validator set and its extra-data come from here.
type PresetSource struct {
	// KeysDir holds the preset metadata.json (validator addresses, BLS public
	// keys, and RLP extra-data).
	KeysDir string
	// ChainID, when non-zero, overrides the manifest chain id in the built
	// genesis (the custom-chain-id boundary; the DSL env layer sets it).
	ChainID int64
}

// Genesis loads the preset, takes the first `validators` entries, and delegates
// to the chain's consensus family to build the genesis, applying any launch
// config overrides and overlay. ctx is accepted for future remote preset
// sources; the local metadata read does not use it.
func (s PresetSource) Genesis(_ context.Context, plugin registry.ChainPlugin, req Request) (Artifacts, error) {
	validators := req.Validators
	preset, err := store.LoadPreset(s.KeysDir)
	if err != nil {
		return Artifacts{}, fmt.Errorf("genesis: preset source: %w", err)
	}
	net := preset.NetworkFor(validators)
	gen, err := Build(plugin, Inputs{
		Validators: net.Validators,
		BLSKeys:    net.BLSKeys,
		ExtraData:  net.ExtraData,
		Members:    net.Members,
		Alloc:      net.Alloc,
		ChainID:    s.ChainID,
	})
	if err != nil {
		return Artifacts{}, fmt.Errorf("genesis: preset source: %w", err)
	}
	// A wbft-family network is one file: the validator set is inside the
	// genesis, so nothing else has to reach a later step.
	return Artifacts{Genesis: gen}, nil
}

// Config is everything a caller can say about how a network's genesis is
// produced. It is the same set for every family; which of it a particular
// family's source consumes is that family's business.
type Config struct {
	// KeysDir is the key set the network's identities come from.
	KeysDir string
	// Binary is the node executable, for a family whose genesis its own binary
	// writes.
	Binary string
	// ChainID overrides the manifest's chain id when non-zero.
	ChainID int64
	// ConfigOverrides sets bare keys in the genesis `config` object.
	ConfigOverrides map[string]string
	// Overlay is a genesis JSON fragment deep-merged into the built
	Overlay []byte
	// Files stages the generator's inputs and reads its output. Nil is the local
	// filesystem; a remote store runs a binary-written genesis on the target,
	// where the binary lives. Ignored by families whose genesis is in-process.
	Files filestore.Store
	// WorkDir is the directory on Files' machine where the generator's config,
	// template, and output live. Empty means a local temporary directory (valid
	// only with a local Files); a remote store needs a real path on the target.
	WorkDir string
	// Runner runs the generating binary on Files' machine. Nil runs it in this
	// process (os/exec) — correct only for a local target.
	Runner CommandRunner
}

// Compose produces a network's genesis: the family's own base through its
// source, then the caller's customizations applied the same way to whatever
// it produced.
//
// It exists so that "which source does this family need" is answered once.
// That question was being answered in five places — two composition paths
// branching on the family id and three more hardcoding a source — and the
// answers had drifted: a genesis overlay reached a wemix network through the
// step surface and was dropped on the engine one, because the customization
// lived inside the source that only one family uses.
func Compose(ctx context.Context, plugin registry.ChainPlugin, req Request, cfg Config) (Artifacts, error) {
	art, err := SourceFor(plugin, cfg).Genesis(ctx, plugin, req)
	if err != nil {
		return Artifacts{}, err
	}
	gen, err := Customize(art.Genesis, NetworkOptions{
		ConfigOverrides: cfg.ConfigOverrides,
		Overlay:         cfg.Overlay,
	})
	if err != nil {
		return Artifacts{}, err
	}
	art.Genesis = gen
	return art, nil
}

// SourceProvider is the capability a consensus family declares when its
// genesis is not a template substitution: the family supplies its own Source.
// It is discovered by type assertion, so this package names no family — the
// alternative was a branch on the family id here, which is how the wemix path
// came to be special-cased in two callers and missed in a third.
type SourceProvider interface {
	GenesisSource(cfg Config) Source
}

// SourceFor returns the source a chain's family builds its genesis with: the
// family's own when it provides one, else the preset template substitution.
func SourceFor(plugin registry.ChainPlugin, cfg Config) Source {
	if p, ok := plugin.Family().(SourceProvider); ok {
		return p.GenesisSource(cfg)
	}
	return PresetSource{KeysDir: cfg.KeysDir, ChainID: cfg.ChainID}
}
