package poa

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/0xmhha/chainbench/internal/core/filestore"
	"github.com/0xmhha/chainbench/internal/core/genesis"
	"github.com/0xmhha/chainbench/internal/core/keyring"
	"github.com/0xmhha/chainbench/internal/core/keyring/store"
	"github.com/0xmhha/chainbench/internal/core/node"
	"github.com/0xmhha/chainbench/internal/core/registry"
	"os"
	"os/exec"
	"path"
)

// GenesisSource produces a wemix genesis the way the chain actually makes
// one: it assembles the governance config, hands it and a prepared template to
// the binary, and returns what the binary wrote — plus the config itself, which
// deploy-governance needs later in the bring-up.
//
// The substituting path this replaces produced a genesis that initialized
// cleanly and left the node running ethash with no wemix namespace. Nothing in
// Go can write this file correctly: the alloc, the extraData bootnode encoding
// and the wemix fork config come from the binary.
type GenesisSource struct {
	// KeysDir is the key set the network's identities come from.
	KeysDir string
	// Binary is the gwemix executable that generates the genesis.
	Binary string
	// ChainID overrides the manifest's chain id when non-zero.
	ChainID int64
	// Env is the governance policy; the zero value takes DefaultEnv.
	Env *Env
	// Run executes the binary. Injected so the assembly is testable without
	// one; nil uses os/exec. A remote run pairs with a remote Files.
	Run Runner
	// Files stages the config and template and reads the produced genesis back.
	// Nil is the local filesystem; a remote store puts the inputs where the
	// binary that reads them runs (the target host).
	Files filestore.Store
	// WorkDir is where the intermediate template and config are written before
	// the binary reads them; empty uses a local temporary directory that is
	// removed (valid only when Files is local).
	WorkDir string
}

// ConfigFileName is the name the governance config takes on the target. The
// bring-up's deploy-governance action reads it back under this name.
const ConfigFileName = "wemix-config.json"

// Genesis assembles the config, runs the generator, and returns both files.
func (s GenesisSource) Genesis(ctx context.Context, plugin registry.ChainPlugin, req genesis.Request) (genesis.Artifacts, error) {
	if s.Binary == "" {
		return genesis.Artifacts{}, fmt.Errorf("poa: genesis: no binary — this chain's genesis is generated by gwemix, not substituted")
	}
	if req.Nodes == nil {
		return genesis.Artifacts{}, fmt.Errorf("poa: genesis: no placement — the governance config names the producer's host and p2p port, so the network has to be placed first")
	}
	preset, err := store.LoadPreset(s.KeysDir)
	if err != nil {
		return genesis.Artifacts{}, fmt.Errorf("poa: genesis: %w", err)
	}
	cfg, err := s.config(preset, req)
	if err != nil {
		return genesis.Artifacts{}, err
	}
	if err := cfg.Validate(); err != nil {
		return genesis.Artifacts{}, fmt.Errorf("poa: genesis: %w", err)
	}
	cfgBytes, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return genesis.Artifacts{}, fmt.Errorf("poa: genesis: encode config: %w", err)
	}

	chainID := plugin.Manifest().ChainID
	if s.ChainID != 0 {
		chainID = s.ChainID
	}
	// The generator passes the template's config through untouched, so the
	// chain id has to be in the template before it runs or the network comes
	// up on whatever the template shipped with.
	tmpl, err := PrepareTemplate(plugin.GenesisTemplate(), chainID, cfg.Members[0].Addr)
	if err != nil {
		return genesis.Artifacts{}, fmt.Errorf("poa: genesis: %w", err)
	}

	// Files stages the inputs where the binary reads them: the local filesystem
	// for a local target, the target host for a remote one. A local run with no
	// WorkDir gets a temporary directory that is removed; a remote run needs a
	// real path on the target, so it does not default one.
	files := s.Files
	dir := s.WorkDir
	if files == nil {
		files = filestore.Local{}
		if dir == "" {
			tmp, err := os.MkdirTemp("", "cb-wemix-genesis-")
			if err != nil {
				return genesis.Artifacts{}, fmt.Errorf("poa: genesis: %w", err)
			}
			defer func() { _ = os.RemoveAll(tmp) }()
			dir = tmp
		}
	}
	if dir == "" {
		return genesis.Artifacts{}, fmt.Errorf("poa: genesis: a remote genesis needs a work directory on the target")
	}
	cfgPath := path.Join(dir, ConfigFileName)
	tmplPath := path.Join(dir, "genesis-template.json")
	outPath := path.Join(dir, "genesis.json")
	for p, content := range map[string][]byte{cfgPath: cfgBytes, tmplPath: tmpl} {
		if err := files.Write(ctx, p, content, 0o644); err != nil {
			return genesis.Artifacts{}, fmt.Errorf("poa: genesis: write %s: %w", path.Base(p), err)
		}
	}

	run := s.Run
	if run == nil {
		run = ExecRunner
	}
	if err := GenerateGenesis(ctx, run, s.Binary, cfgPath, tmplPath, outPath); err != nil {
		return genesis.Artifacts{}, fmt.Errorf("poa: genesis: %w", err)
	}
	gen, err := files.Read(ctx, outPath)
	if err != nil {
		return genesis.Artifacts{}, fmt.Errorf("poa: genesis: read generated genesis: %w", err)
	}
	return genesis.Artifacts{
		Genesis: gen,
		Extra:   map[string][]byte{ConfigFileName: cfgBytes},
	}, nil
}

// config assembles the governance config from the key set and the placement.
//
// The producer is the network's boot member: it is the node the bootstrap runs
// on, and the config names it by address, devp2p id, host and p2p port. Every
// key-set identity is funded, so a test does not have to arrange for gas before
// it can do anything.
func (s GenesisSource) config(preset keyring.Preset, req genesis.Request) (Config, error) {
	boot, ok := bootPlacement(req.Nodes)
	if !ok {
		return Config{}, fmt.Errorf("poa: genesis: the placement has no producer to bootstrap from")
	}
	entry, ok := preset.Node(boot.Index)
	if !ok {
		return Config{}, fmt.Errorf("poa: genesis: the key set has no identity for node%d", boot.Index)
	}
	env := DefaultEnv()
	if s.Env != nil {
		env = *s.Env
	}
	net := preset.NetworkFor(req.Validators)
	accounts := []Account{{Addr: entry.Address, Balance: DefaultAccountBalance()}}
	for _, v := range net.Validators {
		if v == entry.Address {
			continue
		}
		accounts = append(accounts, Account{Addr: v, Balance: DefaultAccountBalance()})
	}
	// Every producer is a member, not just the boot node.
	//
	// Measured: with only the boot node in the member list the cluster forms
	// and the chain runs, and every block is sealed by that one node — the
	// others join the p2p network, never join etcd, and never enter the
	// rotation. Membership is what makes a producer produce.
	members := make([]Member, 0, 4)
	for _, p := range req.Nodes.Placements() {
		if !node.Is(p.Role, node.RoleBoot) && !node.Is(p.Role, node.RoleBP) {
			continue
		}
		e, ok := preset.Node(p.Index)
		if !ok {
			return Config{}, fmt.Errorf("poa: genesis: the key set has no identity for node%d", p.Index)
		}
		members = append(members, Member{
			Addr:  e.Address,
			Stake: env.StakingMin,
			Name:  string(p.Label),
			ID:    "0x" + e.PublicKey,
			IP:    p.Host,
			Port:  p.Ports.P2P,
			// Exactly one bootnode: the config is rejected otherwise, and the
			// bring-up's first phase launches that node alone.
			Bootnode: p.Index == boot.Index,
		})
	}

	return Config{
		ExtraData:    "chainbench",
		Staker:       entry.Address,
		Ecosystem:    entry.Address,
		Maintenance:  entry.Address,
		FeeCollector: entry.Address,
		Env:          env,
		Members:      members,
		Accounts:     accounts,
	}, nil
}

// bootPlacement is the node the bootstrap runs on: the last producer in the
// placement, which is also the node the family's boot phase launches alone. It
// is the highest-index producer so the bring-up starts from the back and works
// forward — the boot node comes up first, then each remaining producer joins one
// at a time. BringUpPhases picks the same node; the two must agree, because the
// genesis names this node the sole initial member and the boot phase forms the
// cluster on it.
func bootPlacement(m *node.Map) (node.Placement, bool) {
	var boot node.Placement
	found := false
	for _, p := range m.Placements() {
		if node.Is(p.Role, node.RoleBoot) || node.Is(p.Role, node.RoleBP) {
			boot = p
			found = true
		}
	}
	return boot, found
}

// ExecRunner runs the binary for real.
func ExecRunner(ctx context.Context, name string, args ...string) ([]byte, error) {
	return exec.CommandContext(ctx, name, args...).CombinedOutput()
}

// GenesisSource is the family's own genesis source: this family's genesis is
// written by its binary from a governance config, not substituted into a
// template. Declaring it here is what lets core/genesis pick it without
// naming the family.
func (Family) GenesisSource(cfg genesis.Config) genesis.Source {
	return GenesisSource{
		KeysDir: cfg.KeysDir, Binary: cfg.Binary, ChainID: cfg.ChainID,
		// The staging seam: a remote target passes its file store, a work
		// directory on the host, and a runner that execs the binary there. A
		// local target leaves them zero and the source runs in this process.
		Files: cfg.Files, WorkDir: cfg.WorkDir, Run: Runner(cfg.Runner),
	}
}
