// Package poa implements the "poa" consensus family used by the wemix chain
// (decision D9): etcd-based membership with governance contracts deployed by a
// boot node, consensus RPC under the "wemix" namespace. The etcd bootstrap
// sequence (boot node -> deploy governance -> init etcd -> start others, per
// ../script/wemix-upgrade) attaches to Bootstrap when the setup pipeline lands
// in phase G7; G0 provides the static, RPC-facing surface.
package poa

import (
	"fmt"
	"github.com/0xmhha/chainbench/internal/core/node"
	"github.com/0xmhha/chainbench/internal/core/registry"
)

// Family is the poa (wemix/etcd) consensus-family strategy.
type Family struct{}

// New returns the poa consensus family.
func New() Family { return Family{} }

// FamilyID names this consensus family. It is exported so a caller can branch
// on the family it composed without spelling the string itself.
const FamilyID = "poa"

func (Family) ID() string               { return FamilyID }
func (Family) RPCNamespace() string     { return "wemix" }
func (Family) ValidatorsMethod() string { return "wemix_getValidators" }

// BuildGenesis renders the poa base genesis: the validator set is not in the
// genesis (membership is set at bootstrap), so only ChainID and Coinbase apply.
// BuildGenesis refuses: this family's genesis is not a substitution.
//
// The dispatch exists for families whose genesis is their template with the
// validator set written into it. wemix resolves membership at bootstrap through
// governance contracts and etcd, and its genesis is generated by the binary
// from a governance config. Returning the substituted template here — which is
// what this did — handed back a genesis that initialized cleanly and produced a
// chain running ethash with no wemix namespace. An error naming the right path
// is strictly better than a network that starts and is silently the wrong one.
func (Family) BuildGenesis(template []byte, p registry.GenesisParams) ([]byte, error) {
	return nil, fmt.Errorf(
		"poa: a wemix genesis is generated by the binary from a governance config, not substituted from a template — use the wemix genesis source (PrepareTemplate then GenerateGenesis)")
}

// StartFlags returns the node launch flags for a role. The boot node performs
// governance deployment and etcd initialization out of band.
func (Family) StartFlags(role node.Role) []string {
	flags := []string{
		"--allow-insecure-unlock",
	}
	// Both spellings of the producing role seal (see the wbft family): a
	// producer launched without --mine stalls the chain, and which word the
	// composition recorded must not decide that.
	canonical, err := node.NormalizeRole(string(role))
	if err == nil && (canonical == node.RoleBP || canonical == node.RoleBoot) {
		flags = append(flags, "--mine")
	}
	return flags
}

// BringUpPhases: the producer starts alone, carries the governance deploy and
// the etcd init, and only then do the rest join.
//
// The order is not a preference. The bootstrap forms an etcd cluster of one and
// the remaining nodes join it; run with everything already up, the cluster
// stays empty and the chain never produces — the failure that made this family
// impossible to bring up through the ordinary path.
//
// The boot node is the first producer in the plan. Actions are named here and
// executed by whoever wired them: this package says what must happen between
// the groups, not how.
func (Family) BringUpPhases(roles []node.Role) []registry.Phase {
	producers := make([]int, 0, len(roles))
	endpoints := make([]int, 0, len(roles))
	for i, r := range roles {
		if node.Is(r, node.RoleBoot) || node.Is(r, node.RoleBP) {
			producers = append(producers, i+1)
		} else {
			endpoints = append(endpoints, i+1)
		}
	}
	if len(producers) == 0 {
		// No producer to bootstrap from; let the caller's own validation say
		// so rather than inventing a phase over an empty group.
		return []registry.Phase{{Name: "all"}}
	}
	// The boot node is the last (highest-index) producer. It comes up alone and
	// forms the etcd cluster of one; genesis names the same node the sole initial
	// member, so bootPlacement must pick it too.
	boot := producers[len(producers)-1]
	phases := []registry.Phase{{
		Name:    "boot",
		Nodes:   []int{boot},
		Actions: []string{ActionDeployGovernance, ActionEtcdInit, ActionVerifyEtcd},
	}}
	// Each remaining producer starts and joins on its own phase, highest index
	// first. One node syncs at a time, from a set that is already the canonical
	// chain, so no two producers race to seal a competing block before they have
	// it — the flaky "unauthorized block" a simultaneous start produced on a
	// spread network. The join concerns the joining node; ActionsOn names it.
	for i := len(producers) - 2; i >= 0; i-- {
		p := producers[i]
		phases = append(phases, registry.Phase{
			Name:      fmt.Sprintf("join-node%d", p),
			Nodes:     []int{p},
			Actions:   []string{ActionEtcdJoin},
			ActionsOn: p,
		})
	}
	// Endpoints seal nothing, so they never fork; bring them up together at the
	// end, once the producer set is a formed cluster serving one chain.
	if len(endpoints) > 0 {
		phases = append(phases, registry.Phase{Name: "endpoints", Nodes: endpoints})
	}
	return phases
}

// The bring-up actions this family names. They are strings at the boundary because
// the core does not know what they mean; these constants exist so the family
// and whoever wires the executor agree on the spelling.
const (
	// ActionDeployGovernance deploys the governance contracts over the
	// producer's IPC.
	ActionDeployGovernance = "deploy-governance"
	// ActionEtcdInit forms the etcd cluster. Its return value proves nothing —
	// it is null on success — so it is always followed by a verification.
	ActionEtcdInit = "etcd-init"
	// ActionVerifyEtcd confirms the cluster formed: admin.wemixInfo.etcd.cluster
	// must be non-empty, which is the only evidence the init worked.
	ActionVerifyEtcd = "verify-etcd"
	// ActionEtcdJoin brings the remaining producers into the cluster the boot
	// node formed. It is not optional decoration: a producer outside the
	// cluster stays out of the sealing rotation, so a network without it has
	// one node writing every block while the others merely follow.
	//
	// The chain's own join is a handshake over the eth wire protocol, not a
	// local call — the joiner asks a peer (admin.etcdJoin names the peer to
	// ask, not the joiner), that peer adds it and replies with the cluster
	// string, and the joiner starts its embedded server against it. Both ends
	// must be governance members for the handshake to be answered at all.
	ActionEtcdJoin = "etcd-join"
)

// PortReservation: a poa node embeds etcd, which listens on two further ports
// — peer at p2p+1 and client at p2p+2 (go-wemix wemix/etcdutil.go). Three is
// the span, and a step of two — which the previous global rule accepted — puts
// the next node's p2p port on this node's etcd client.
func (Family) PortReservation() node.Reservation {
	return node.Reservation{P2PSpan: 3, RPCSpan: 3}
}

// SupportsRole: poa produces blocks and serves endpoints, and one producer
// carries the governance bootstrap. It has no proxy tier — etcd occupies that
// place — so a pn declared here is refused rather than quietly ignored.
func (Family) SupportsRole(role node.Role) bool {
	canonical, err := node.NormalizeRole(string(role))
	if err != nil {
		return false
	}
	switch canonical {
	case node.RoleBP, node.RoleEN, node.RoleBoot:
		return true
	default:
		return false
	}
}
