package engine

import (
	"context"
	"fmt"

	"github.com/0xmhha/chainbench/internal/core/genesis"
	"github.com/0xmhha/chainbench/internal/core/keyring"
	"github.com/0xmhha/chainbench/internal/core/netmap"
	"github.com/0xmhha/chainbench/internal/core/registry"
)

// GenesisSource produces a network's genesis bytes for a chain plugin, sized to
// the active validator count. It is a seam so BuildEnv does not depend on where
// the validator set and RLP extra-data come from: a baked preset today, and a
// live key deriver (once a Go extra-data encoder exists) later.
type GenesisSource interface {
	// Genesis builds the genesis artifacts for plugin from the network being
	// composed.
	Genesis(ctx context.Context, plugin registry.ChainPlugin, req GenesisRequest) (GenesisArtifacts, error)
}

// GenesisRequest is the network a genesis is being built for.
//
// Validators alone was enough while every family kept its validator set inside
// the genesis. A wemix genesis does not: its governance config names the
// producer by address, public key, host and p2p port, so the source has to know
// where the network will actually run. Passing the placement is what lets the
// family that needs it read it, and the one that does not ignore it.
type GenesisRequest struct {
	// Validators is how many of the key set's entries produce blocks; <=0 is
	// the whole set.
	Validators int
	// Nodes is the resolved placement, or nil when a caller has none (a
	// fixed-port setup path). A family that needs an address errors on nil
	// rather than inventing one.
	Nodes *netmap.Map
}

// GenesisArtifacts is what a genesis step produces. For most families that is
// one file; for wemix it is not.
//
// A wemix genesis is generated by the binary from a governance config, and that
// same config is then an input to deploy-governance during the bring-up. The
// step's by-product has to reach a later step, so the source returns it here
// instead of the caller reconstructing it — reconstructing is how two callers
// come to disagree about what the network was configured with.
type GenesisArtifacts struct {
	// Genesis is the genesis.json bytes.
	Genesis []byte
	// Extra are further files the family needs on the target, keyed by the
	// name they take there ("wemix-config.json"). Families that need none
	// leave it nil.
	Extra map[string][]byte
}

// PresetGenesisSource builds genesis from a baked preset key set. The preset is
// the only source of a wbft-family network's RLP extra-data: the consensus
// family substitutes the extra-data into its template but does not compute it,
// so a freshly generated random key set cannot seed a valid wbft genesis on its
// own. Node identity/account keys (nodekey, unlock) come from the key registry;
// the validator set and its extra-data come from here.
type PresetGenesisSource struct {
	// KeysDir holds the preset metadata.json (validator addresses, BLS public
	// keys, and RLP extra-data).
	KeysDir string
	// ChainID, when non-zero, overrides the manifest chain id in the built
	// genesis (the custom-chain-id seam; the DSL env layer sets it).
	ChainID int64
	// ConfigOverrides sets keys in the genesis `config` object after the build —
	// the delayed-fork seam (e.g. {"bohoBlock":"10"} from
	// `setup --set genesis.overrides.*`). Empty applies none.
	ConfigOverrides map[string]string
	// Overlay is a JSON genesis fragment deep-merged into the built genesis
	// (extra alloc or system-contract params, from `setup --genesis-overlay`).
	// Empty applies none.
	Overlay []byte
}

// Genesis loads the preset, takes the first `validators` entries, and delegates
// to the chain's consensus family to build the genesis, applying any launch
// config overrides and overlay. ctx is accepted for future remote preset
// sources; the local metadata read does not use it.
func (s PresetGenesisSource) Genesis(_ context.Context, plugin registry.ChainPlugin, req GenesisRequest) (GenesisArtifacts, error) {
	validators := req.Validators
	preset, err := keyring.LoadPreset(s.KeysDir)
	if err != nil {
		return GenesisArtifacts{}, fmt.Errorf("engine: genesis source: %w", err)
	}
	net := preset.NetworkFor(validators)
	gen, err := genesis.BuildNetwork(plugin, genesis.Inputs{
		Validators: net.Validators,
		BLSKeys:    net.BLSKeys,
		ExtraData:  net.ExtraData,
		Members:    net.Members,
		Alloc:      net.Alloc,
		ChainID:    s.ChainID,
	}, genesis.NetworkOptions{ConfigOverrides: s.ConfigOverrides, Overlay: s.Overlay})
	if err != nil {
		return GenesisArtifacts{}, fmt.Errorf("engine: genesis source: %w", err)
	}
	// A wbft-family network is one file: the validator set is inside the
	// genesis, so nothing else has to reach a later step.
	return GenesisArtifacts{Genesis: gen}, nil
}
