package engine

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"

	"github.com/0xmhha/chainbench/internal/consensus/poa"
	"github.com/0xmhha/chainbench/internal/core/keyring"
	"github.com/0xmhha/chainbench/internal/core/netmap"
	"github.com/0xmhha/chainbench/internal/core/node"
	"github.com/0xmhha/chainbench/internal/core/registry"
)

// WemixGenesisSource produces a wemix genesis the way the chain actually makes
// one: it assembles the governance config, hands it and a prepared template to
// the binary, and returns what the binary wrote — plus the config itself, which
// deploy-governance needs later in the bring-up.
//
// The substituting path this replaces produced a genesis that initialized
// cleanly and left the node running ethash with no wemix namespace. Nothing in
// Go can write this file correctly: the alloc, the extraData bootnode encoding
// and the wemix fork config come from the binary.
type WemixGenesisSource struct {
	// KeysDir is the key set the network's identities come from.
	KeysDir string
	// Binary is the gwemix executable that generates the genesis.
	Binary string
	// ChainID overrides the manifest's chain id when non-zero.
	ChainID int64
	// Env is the governance policy; the zero value takes poa.DefaultEnv.
	Env *poa.Env
	// Run executes the binary. Injected so the assembly is testable without
	// one; nil uses os/exec.
	Run poa.Runner
	// WorkDir is where the intermediate template and config are written before
	// the binary reads them; empty uses a temporary directory that is removed.
	WorkDir string
}

// wemixConfigName is the name the governance config takes on the target. The
// bring-up's deploy-governance action reads it back under this name.
const wemixConfigName = "wemix-config.json"

// Genesis assembles the config, runs the generator, and returns both files.
func (s WemixGenesisSource) Genesis(ctx context.Context, plugin registry.ChainPlugin, req GenesisRequest) (GenesisArtifacts, error) {
	if s.Binary == "" {
		return GenesisArtifacts{}, fmt.Errorf("engine: wemix genesis: no binary — this chain's genesis is generated by gwemix, not substituted")
	}
	if req.Nodes == nil {
		return GenesisArtifacts{}, fmt.Errorf("engine: wemix genesis: no placement — the governance config names the producer's host and p2p port, so the network has to be placed first")
	}
	preset, err := keyring.LoadPreset(s.KeysDir)
	if err != nil {
		return GenesisArtifacts{}, fmt.Errorf("engine: wemix genesis: %w", err)
	}
	cfg, err := s.config(preset, req)
	if err != nil {
		return GenesisArtifacts{}, err
	}
	if err := cfg.Validate(); err != nil {
		return GenesisArtifacts{}, fmt.Errorf("engine: wemix genesis: %w", err)
	}
	cfgBytes, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return GenesisArtifacts{}, fmt.Errorf("engine: wemix genesis: encode config: %w", err)
	}

	chainID := plugin.Manifest().ChainID
	if s.ChainID != 0 {
		chainID = s.ChainID
	}
	// The generator passes the template's config through untouched, so the
	// chain id has to be in the template before it runs or the network comes
	// up on whatever the template shipped with.
	tmpl, err := poa.PrepareTemplate(plugin.GenesisTemplate(), chainID, cfg.Members[0].Addr)
	if err != nil {
		return GenesisArtifacts{}, fmt.Errorf("engine: wemix genesis: %w", err)
	}

	dir := s.WorkDir
	if dir == "" {
		tmp, err := os.MkdirTemp("", "cb-wemix-genesis-")
		if err != nil {
			return GenesisArtifacts{}, fmt.Errorf("engine: wemix genesis: %w", err)
		}
		defer func() { _ = os.RemoveAll(tmp) }()
		dir = tmp
	}
	cfgPath := filepath.Join(dir, wemixConfigName)
	tmplPath := filepath.Join(dir, "genesis-template.json")
	outPath := filepath.Join(dir, "genesis.json")
	for path, content := range map[string][]byte{cfgPath: cfgBytes, tmplPath: tmpl} {
		if err := os.WriteFile(path, content, 0o644); err != nil {
			return GenesisArtifacts{}, fmt.Errorf("engine: wemix genesis: write %s: %w", filepath.Base(path), err)
		}
	}

	run := s.Run
	if run == nil {
		run = execRunner
	}
	if err := poa.GenerateGenesis(ctx, run, s.Binary, cfgPath, tmplPath, outPath); err != nil {
		return GenesisArtifacts{}, fmt.Errorf("engine: wemix genesis: %w", err)
	}
	gen, err := os.ReadFile(outPath)
	if err != nil {
		return GenesisArtifacts{}, fmt.Errorf("engine: wemix genesis: read generated genesis: %w", err)
	}
	return GenesisArtifacts{
		Genesis: gen,
		Extra:   map[string][]byte{wemixConfigName: cfgBytes},
	}, nil
}

// config assembles the governance config from the key set and the placement.
//
// The producer is the network's boot member: it is the node the bootstrap runs
// on, and the config names it by address, devp2p id, host and p2p port. Every
// key-set identity is funded, so a test does not have to arrange for gas before
// it can do anything.
func (s WemixGenesisSource) config(preset keyring.Preset, req GenesisRequest) (poa.Config, error) {
	boot, ok := bootPlacement(req.Nodes)
	if !ok {
		return poa.Config{}, fmt.Errorf("engine: wemix genesis: the placement has no producer to bootstrap from")
	}
	entry, ok := preset.Node(boot.Index)
	if !ok {
		return poa.Config{}, fmt.Errorf("engine: wemix genesis: the key set has no identity for node%d", boot.Index)
	}
	env := poa.DefaultEnv()
	if s.Env != nil {
		env = *s.Env
	}
	net := preset.NetworkFor(req.Validators)
	accounts := []poa.Account{{Addr: entry.Address, Balance: poa.DefaultAccountBalance()}}
	for _, v := range net.Validators {
		if v == entry.Address {
			continue
		}
		accounts = append(accounts, poa.Account{Addr: v, Balance: poa.DefaultAccountBalance()})
	}
	// Every producer is a member, not just the boot node.
	//
	// Measured: with only the boot node in the member list the cluster forms
	// and the chain runs, and every block is sealed by that one node — the
	// others join the p2p network, never join etcd, and never enter the
	// rotation. Membership is what makes a producer produce.
	members := make([]poa.Member, 0, 4)
	for _, p := range req.Nodes.Placements() {
		if !netmap.Is(p.Role, node.RoleBoot) && !netmap.Is(p.Role, node.RoleBP) {
			continue
		}
		e, ok := preset.Node(p.Index)
		if !ok {
			return poa.Config{}, fmt.Errorf("engine: wemix genesis: the key set has no identity for node%d", p.Index)
		}
		members = append(members, poa.Member{
			Addr:  e.Address,
			Stake: env.StakingMin,
			Name:  string(p.Label),
			ID:    "0x" + e.PublicKey,
			IP:    p.Host,
			Port:  p.Ports.P2P,
			// Exactly one bootnode: the config is rejected otherwise, and the
			// bring-up's first phase launches that node alone.
			Bootnode: p.Index == boot.Index,
		})
	}

	return poa.Config{
		ExtraData:    "chainbench",
		Staker:       entry.Address,
		Ecosystem:    entry.Address,
		Maintenance:  entry.Address,
		FeeCollector: entry.Address,
		Env:          env,
		Members:      members,
		Accounts:     accounts,
	}, nil
}

// bootPlacement is the node the bootstrap runs on: the first producer in the
// placement, which is also the node the family's boot phase launches alone.
func bootPlacement(m *netmap.Map) (netmap.Placement, bool) {
	for _, p := range m.Placements() {
		if netmap.Is(p.Role, node.RoleBoot) || netmap.Is(p.Role, node.RoleBP) {
			return p, true
		}
	}
	return netmap.Placement{}, false
}

// execRunner runs the binary for real.
func execRunner(ctx context.Context, name string, args ...string) ([]byte, error) {
	return exec.CommandContext(ctx, name, args...).CombinedOutput()
}
