package testengine_test

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
	"time"

	_ "github.com/0xmhha/chainbench/internal/chains/wemix" // register the wemix plugin

	"github.com/0xmhha/chainbench/internal/chainsetup"
	"github.com/0xmhha/chainbench/internal/testengine"
)

// TestWemix_Live_BringUp is the family track's gate: a wemix network brought
// up through the suite path — genesis generated by the binary, producer
// launched alone, governance deployed, etcd formed, the rest joining — and
// then producing blocks.
//
// Block production alone does not prove it: an un-bootstrapped wemix node
// falls back to ethash and advances the chain happily, which is why the
// bring-up's own verify-etcd gate matters — a network that composes at all
// has a formed cluster behind it.
//
// Gated on GWEMIX_BIN; CI has no chain binary and skips.
func TestWemix_Live_BringUp(t *testing.T) {
	bin := os.Getenv("GWEMIX_BIN")
	if bin == "" {
		t.Skip("set GWEMIX_BIN to the go-wemix gwemix binary to run this")
	}
	// geth's IPC socket path has a 104-character limit, so the workspace
	// stays short rather than living under t.TempDir().
	ws, err := os.MkdirTemp("/tmp", "cbw")
	if err != nil {
		t.Fatal(err)
	}
	defer func() {
		// A failed live run is worth reading: keep the workspace and say where.
		if t.Failed() {
			t.Logf("workspace kept at %s", ws)
			return
		}
		_ = os.RemoveAll(ws)
	}()

	spec, err := json.Marshal(map[string]any{
		"schemaVersion":    "1",
		"id":               "wemix-live",
		"applicableChains": "wemix",
		"chain":            map[string]any{"name": "wemix", "binary": bin},
		"assertions": []map[string]any{
			{"assert": "blockNumber", "compare": "Greater", "expected": "0"},
		},
	})
	if err != nil {
		t.Fatal(err)
	}
	specPath := filepath.Join(ws, "wemix-live.json")
	if err := os.WriteFile(specPath, spec, 0o644); err != nil {
		t.Fatal(err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 6*time.Minute)
	defer cancel()

	out, err := testengine.RunSuite(ctx, chainsetup.Deps{}, testengine.RunSuiteIn{
		SpecPaths:  []string{specPath},
		DataDir:    ws,
		Binary:     bin,
		KeysDir:    filepath.Join(repoRoot(t), "keys", "preset"),
		Validators: 4,
		WaitBlocks: 1,
	})
	if err != nil {
		t.Fatalf("RunSuite: %v (setup %v)", err, out.SetupSteps)
	}
	if out.Summary.Summary.Pass != 1 {
		t.Fatalf("summary = %+v (session %s)", out.Summary.Summary, out.SessionRoot)
	}
}
