package testengine_test

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	_ "github.com/0xmhha/chainbench/internal/chains/wemix" // register the wemix plugin

	"github.com/0xmhha/chainbench/internal/testengine"
)

// TestWemix_Live_BringUp is the family track's gate: a wemix network brought up
// through the ordinary engine path — genesis generated by the binary, producer
// launched alone, governance deployed, etcd formed, the rest joining — and then
// producing blocks.
//
// Block production alone does not prove it: an un-bootstrapped wemix node falls
// back to ethash and advances the chain happily, which is why the etcd cluster
// is checked too.
//
// With four validators the gate also covers the join. The rest phase asks each
// remaining producer to join the cluster the boot node formed and refuses to
// continue unless the cluster names all four, so a network that comes up here
// is one where every producer can take a turn at sealing — the state a
// single-member cluster silently denies.
//
// Gated on GWEMIX_BIN; CI has no chain binary and skips.
func TestWemix_Live_BringUp(t *testing.T) {
	bin := os.Getenv("GWEMIX_BIN")
	if bin == "" {
		t.Skip("set GWEMIX_BIN to the go-wemix gwemix binary to run this")
	}
	// geth's IPC socket path has a 104-character limit, so the session root
	// stays short rather than living under t.TempDir().
	root, err := os.MkdirTemp("/tmp", "cbw")
	if err != nil {
		t.Fatal(err)
	}
	defer func() {
		// A failed live run is worth reading: keep the session and say where.
		if t.Failed() {
			t.Logf("session kept at %s", root)
			return
		}
		_ = os.RemoveAll(root)
	}()

	eng, err := testengine.NewLocalEngine(testengine.LocalConfig{
		Chain:        "wemix",
		Binary:       bin,
		KeysDir:      filepath.Join(repoRoot(t), "keys", "preset"),
		ArtifactRoot: root,
		Validators:   4,
	})
	if err != nil {
		t.Fatalf("NewLocalEngine: %v", err)
	}
	spec, err := json.Marshal(map[string]any{
		"schemaVersion":    "1",
		"id":               "wemix-live",
		"applicableChains": "wemix",
		"chain":            map[string]any{"name": "wemix", "binary": bin},
		"assertions": []map[string]any{
			// The chain advancing is what a caller sees. That it advances
			// *because the bootstrap worked* is established during the
			// bring-up, not here: the boot phase's verify-etcd refuses to
			// continue unless admin.wemixInfo.etcd.cluster names a member, so
			// an environment that builds at all has a formed cluster behind it.
			//
			// admin_wemixInfo is not asked over HTTP: it answers on the node's
			// IPC console and returns "method handler crashed" (-32000) through
			// the HTTP RPC, which is a chain-side fault rather than something
			// this test can assert around.
			{"assert": "blockNumber", "compare": "Greater", "expected": "0"},
		},
	})
	if err != nil {
		t.Fatal(err)
	}
	ctx, cancel := context.WithTimeout(context.Background(), 6*time.Minute)
	defer cancel()

	sessionRoot, err := eng.Run(ctx, [][]byte{spec})
	if err != nil {
		t.Fatalf("Engine.Run: %v", err)
	}
	data, err := os.ReadFile(filepath.Join(sessionRoot, "session.json"))
	if err != nil {
		t.Fatalf("read session.json: %v", err)
	}
	var doc struct {
		Summary struct {
			Pass    int `json:"pass"`
			Fail    int `json:"fail"`
			Blocked int `json:"blocked"`
		} `json:"summary"`
	}
	if err := json.Unmarshal(data, &doc); err != nil {
		t.Fatalf("session.json: %v", err)
	}
	if doc.Summary.Pass != 1 {
		t.Fatalf("summary = %+v (session %s)", doc.Summary, sessionRoot)
	}
	_ = strings.TrimSpace
}
