package keyring_test

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"github.com/0xmhha/chainbench/internal/core/keyring/derive"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/0xmhha/chainbench/internal/core/keyring/store"
)

// presetNode is one entry of the shipped keys/preset/metadata.json. The golden
// test reads the deployed fixture rather than a copy so that a preset
// regenerated by a future `keyring new` is checked against the same file the
// chains actually consume.
type presetNode struct {
	Index        int    `json:"index"`
	Nodekey      string `json:"nodekey"`
	PublicKey    string `json:"publicKey"`
	Address      string `json:"address"`
	BLSPublicKey string `json:"blsPublicKey"`
	BLSPoP       string `json:"blsPoP"`
}

func loadPresetNodes(t *testing.T) []presetNode {
	t.Helper()
	path := filepath.Join("..", "..", "..", "keys", "preset", "metadata.json")
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	var meta struct {
		Nodes []presetNode `json:"nodes"`
	}
	if err := json.Unmarshal(raw, &meta); err != nil {
		t.Fatalf("parse %s: %v", path, err)
	}
	if len(meta.Nodes) == 0 {
		t.Fatalf("%s has no nodes", path)
	}
	return meta.Nodes
}

// TestDerive_GoldenAgainstShippedPreset is the golden gate: every field of the
// shipped preset must be reproducible from its nodekey alone, byte for byte.
// It is what lets `keyring new` stop shelling out to the go-wbft bootnode
// binary — the derivation is only a drop-in replacement if it is exact.
func TestDerive_GoldenAgainstShippedPreset(t *testing.T) {
	for _, want := range loadPresetNodes(t) {
		t.Run(want.Address, func(t *testing.T) {
			k, err := derive.ParsePrivateKey(want.Nodekey)
			if err != nil {
				t.Fatalf("ParsePrivateKey: %v", err)
			}
			got, err := derive.Derive(k, derive.WithBLS)
			if err != nil {
				t.Fatalf("Derive: %v", err)
			}
			if got.PublicKey != want.PublicKey {
				t.Errorf("devp2p public key\n got %s\nwant %s", got.PublicKey, want.PublicKey)
			}
			if !strings.EqualFold(got.Address, want.Address) {
				t.Errorf("address\n got %s\nwant %s", got.Address, want.Address)
			}
			if got.BLS == nil {
				t.Fatal("WithBLS produced no BLS material")
			}
			if got.BLS.PublicKey != want.BLSPublicKey {
				t.Errorf("BLS public key\n got %s\nwant %s", got.BLS.PublicKey, want.BLSPublicKey)
			}
			// The proof of possession is the field that silently breaks: omit
			// the POP domain separation tag and it still has the right shape
			// but fails verification on-chain.
			if got.BLS.PoP != want.BLSPoP {
				t.Errorf("BLS proof of possession\n got %s\nwant %s", got.BLS.PoP, want.BLSPoP)
			}
		})
	}
}

// TestDerive_AccountOnlyOmitsBLS pins account-only derivation. wemix does not use BLS, so
// deriving without it must leave the material *absent* rather than zeroed — a
// zero-valued BLS key would be indistinguishable from a real one downstream.
func TestDerive_AccountOnlyOmitsBLS(t *testing.T) {
	nodes := loadPresetNodes(t)
	k, err := derive.ParsePrivateKey(nodes[0].Nodekey)
	if err != nil {
		t.Fatalf("ParsePrivateKey: %v", err)
	}
	got, err := derive.Derive(k, derive.AccountOnly)
	if err != nil {
		t.Fatalf("Derive: %v", err)
	}
	if got.BLS != nil {
		t.Errorf("AccountOnly derived BLS material: %+v", got.BLS)
	}
	if got.Address == "" || got.PublicKey == "" {
		t.Errorf("AccountOnly must still derive address and public key, got %+v", got)
	}
}

func TestParseNodekey(t *testing.T) {
	// Borrowed from the preset rather than written inline: a key literal in
	// source is indistinguishable from a real leak to a scanner and to a
	// reviewer, and the preset is already a published fixture.
	valid := loadPresetNodes(t)[0].Nodekey
	cases := []struct {
		name    string
		in      string
		wantErr error
	}{
		{name: "bare hex", in: valid},
		{name: "0x prefixed", in: "0x" + valid},
		{name: "uppercase", in: strings.ToUpper(valid)},
		{name: "surrounding space", in: "  " + valid + "\n"},
		{name: "empty", in: "", wantErr: derive.ErrInvalidPrivateKey},
		{name: "too short", in: valid[:62], wantErr: derive.ErrInvalidPrivateKey},
		{name: "too long", in: valid + "ab", wantErr: derive.ErrInvalidPrivateKey},
		{name: "non-hex", in: strings.Repeat("z", 64), wantErr: derive.ErrInvalidPrivateKey},
		// All-zero is a valid 32-byte string but not a valid secp256k1 scalar,
		// and a node started with it produces an identity nobody can sign for.
		{name: "all zero", in: strings.Repeat("0", 64), wantErr: derive.ErrInvalidPrivateKey},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			k, err := derive.ParsePrivateKey(tc.in)
			if tc.wantErr != nil {
				if !errors.Is(err, tc.wantErr) {
					t.Fatalf("want %v, got %v", tc.wantErr, err)
				}
				return
			}
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if !strings.EqualFold(k.Hex(), valid) {
				t.Errorf("round trip: got %s, want %s", k.Hex(), valid)
			}
		})
	}
}

// TestNewNodekey_UsesInjectedReader keeps generation deterministic under test:
// randomness is a dependency, not a global.
func TestNewNodekey_UsesInjectedReader(t *testing.T) {
	fixed := bytes.Repeat([]byte{0xab}, derive.PrivateKeyLen)
	k, err := derive.NewPrivateKey(bytes.NewReader(fixed))
	if err != nil {
		t.Fatalf("NewPrivateKey: %v", err)
	}
	if got := k.Hex(); got != strings.Repeat("ab", derive.PrivateKeyLen) {
		t.Errorf("got %s", got)
	}

	if _, err := derive.NewPrivateKey(bytes.NewReader(nil)); err == nil {
		t.Error("want error when the reader cannot supply enough entropy")
	}
}

// TestNodekey_DoesNotLeakWhenFormatted guards the one thing that must never
// reach a log or an error string: a formatted Nodekey must not print its bytes.
// Callers that genuinely need the secret have to say so with Hex(), which makes
// every disclosure a visible, greppable decision.
func TestNodekey_DoesNotLeakWhenFormatted(t *testing.T) {
	secret := loadPresetNodes(t)[0].Nodekey
	k, err := derive.ParsePrivateKey(secret)
	if err != nil {
		t.Fatalf("ParsePrivateKey: %v", err)
	}
	// %#v is covered too: without GoString it would print the raw byte array.
	for _, format := range []string{"%v", "%s", "%+v", "%#v"} {
		out := fmt.Sprintf(format, k)
		if strings.Contains(strings.ToLower(out), secret[:12]) {
			t.Errorf("%s leaked key material: %s", format, out)
		}
		if !strings.Contains(out, "redacted") {
			t.Errorf("%s produced %q, want a redaction marker", format, out)
		}
	}
	if k.Hex() != secret {
		t.Errorf("Hex() must still return the real key, got %s", k.Hex())
	}
}

func FuzzParseNodekey(f *testing.F) {
	// A well-formed seed matters: without one the fuzzer only ever explores
	// rejection paths and never reaches Derive.
	f.Add(strings.Repeat("11", derive.PrivateKeyLen))
	f.Add("0x00")
	f.Add("")
	f.Fuzz(func(t *testing.T, s string) {
		k, err := derive.ParsePrivateKey(s)
		if err != nil {
			return
		}
		// A parsed key must always round-trip, and must always derive.
		if _, err := derive.ParsePrivateKey(k.Hex()); err != nil {
			t.Fatalf("round trip failed for accepted key: %v", err)
		}
		if _, err := derive.Derive(k, derive.WithBLS); err != nil {
			t.Fatalf("accepted key failed to derive: %v", err)
		}
	})
}

// TestPreset_NetworkForNarrowsAndDropsExtraData pins the fix for a defect a
// narrowed set used to carry: extra-data encodes the validator set, so the full
// set's copy names validators a smaller network never starts.
func TestPreset_NetworkForNarrowsAndDropsExtraData(t *testing.T) {
	p, err := store.LoadPreset(filepath.Join("..", "..", "..", "keys", "preset"))
	if err != nil {
		t.Fatalf("LoadPreset: %v", err)
	}
	if p.Network.ExtraData == "" {
		t.Skip("the shipped preset records no extra-data")
	}
	two := p.NetworkFor(2)
	if len(two.Validators) != 2 || len(two.BLSKeys) != 2 {
		t.Fatalf("NetworkFor(2): %d validators, %d BLS keys", len(two.Validators), len(two.BLSKeys))
	}
	if two.ExtraData != "" {
		t.Errorf("NetworkFor(2) kept the full set's extraData: %q", two.ExtraData)
	}
	if p.NetworkFor(0).ExtraData == "" || p.NetworkFor(99).ExtraData == "" {
		t.Error("asking for the whole set should keep its extra-data")
	}
}

// TestEntry_VerifyCatchesDrift is the reason Verify exists: a set whose
// declared identity has drifted from its key material launches a node signing
// as one address while the genesis registers another.
func TestEntry_VerifyCatchesDrift(t *testing.T) {
	p, err := store.LoadPreset(filepath.Join("..", "..", "..", "keys", "preset"))
	if err != nil {
		t.Fatalf("LoadPreset: %v", err)
	}
	drifted := p.Nodes[0]
	drifted.Address = p.Nodes[1].Address
	if err := drifted.Verify(); err == nil {
		t.Fatal("Verify accepted an address that the key does not derive")
	}
}
