package deploy

import (
	"context"
	"encoding/base64"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/0xmhha/chainbench/pkg/core/remote"
)

// NodeKeyInfo is the identity material read from one server: the validator
// coinbase address plus the wemix BLS public key and proof-of-possession,
// derived on the server by `bootnode -nodekey <path> -writeaddress`.
type NodeKeyInfo struct {
	Server    int
	Address   string
	BLSPubKey string // 48-byte hex
	BLSPoP    string // 96-byte hex
}

var hexRe = regexp.MustCompile(`0x[0-9a-fA-F]+`)

// ParseBootnodeOutput parses the three lines `bootnode -writeaddress` prints:
//
//	address: 0x...
//	derived bls public key: 0x...
//	bls PoP (Proof of Possession): 0x...
//
// It tolerates ordering, extra log lines, and stdout/stderr interleaving.
func ParseBootnodeOutput(out string) (NodeKeyInfo, error) {
	var info NodeKeyInfo
	for _, line := range strings.Split(out, "\n") {
		low := strings.ToLower(strings.TrimSpace(line))
		hex := hexRe.FindString(line)
		if hex == "" {
			continue
		}
		switch {
		case strings.Contains(low, "bls pop"), strings.Contains(low, "proof of possession"):
			info.BLSPoP = hex
		case strings.Contains(low, "bls public key"):
			info.BLSPubKey = hex
		case strings.HasPrefix(low, "address:"), strings.Contains(low, " address:"):
			info.Address = hex
		}
	}
	if info.Address == "" {
		return info, fmt.Errorf("deploy: no address in bootnode output:\n%s", out)
	}
	return info, nil
}

// ReadServerKeys reads one server's identity over SSH: it derives the address +
// BLS material via bootnode, and (when localKeystoreDir is non-empty) pulls the
// coinbase and operator keystores to localKeystoreDir/keystore_<i> and
// operator_<i>. env sources the SSH auth fallbacks (nil = no env).
func ReadServerKeys(ctx context.Context, c *Cluster, cr *Credentials, hostKey remote.HostKeyCallback, s Server, localKeystoreDir string, env func(string) string) (NodeKeyInfo, error) {
	rc, err := cr.For(c, s, env)
	if err != nil {
		return NodeKeyInfo{}, err
	}
	p := c.Paths()

	cmd := fmt.Sprintf("%s -nodekey %s -writeaddress", p.Bootnode, shellQuote(p.Nodekey))
	res, err := remote.Exec(ctx, rc, hostKey, cmd)
	if err != nil {
		return NodeKeyInfo{}, fmt.Errorf("deploy: server %d bootnode: %w", s.Index, err)
	}
	info, err := ParseBootnodeOutput(res.Stdout + "\n" + res.Stderr)
	if err != nil {
		return NodeKeyInfo{}, err
	}
	info.Server = s.Index

	if localKeystoreDir != "" {
		if err := os.MkdirAll(localKeystoreDir, 0o700); err != nil {
			return info, err
		}
		for _, ks := range []struct{ remote, local string }{
			{p.CoinbaseKeystore, fmt.Sprintf("keystore_%d", s.Index)},
			{p.OperatorKeystore, fmt.Sprintf("operator_%d", s.Index)},
		} {
			data, err := readRemoteFile(ctx, rc, hostKey, ks.remote)
			if err != nil {
				return info, fmt.Errorf("deploy: server %d read %s: %w", s.Index, ks.remote, err)
			}
			if err := os.WriteFile(filepath.Join(localKeystoreDir, ks.local), data, 0o600); err != nil {
				return info, err
			}
		}
	}
	return info, nil
}

// readRemoteFile reads a remote file's bytes over SSH (base64-piped to avoid
// binary/quoting issues), mirroring how the RemoteDriver ships files the other
// way.
func readRemoteFile(ctx context.Context, rc remote.Credentials, hostKey remote.HostKeyCallback, path string) ([]byte, error) {
	res, err := remote.Exec(ctx, rc, hostKey, "base64 < "+shellQuote(path))
	if err != nil {
		return nil, err
	}
	return base64.StdEncoding.DecodeString(strings.TrimSpace(res.Stdout))
}

// writeRemoteFile writes content to a remote path over SSH (base64-piped),
// creating the parent directory. The reverse of readRemoteFile.
func writeRemoteFile(ctx context.Context, rc remote.Credentials, hostKey remote.HostKeyCallback, remotePath string, content []byte) error {
	enc := base64.StdEncoding.EncodeToString(content)
	dir := shellQuote(pathDir(remotePath))
	cmd := fmt.Sprintf("mkdir -p %s && printf %%s %s | base64 -d > %s", dir, shellQuote(enc), shellQuote(remotePath))
	if _, err := remote.Exec(ctx, rc, hostKey, cmd); err != nil {
		return err
	}
	return nil
}

// pathDir returns the directory portion of a slash path (remote paths are POSIX).
func pathDir(p string) string {
	if i := strings.LastIndex(p, "/"); i > 0 {
		return p[:i]
	}
	return "."
}

// shellQuote single-quotes a path for safe remote shell use.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// FormatAccountsFragment renders a `validators:` YAML fragment for the accounts
// file from read key info, so the operator does not transcribe by hand.
func FormatAccountsFragment(infos []NodeKeyInfo) string {
	var b strings.Builder
	b.WriteString("# generated by `chainbench remote keys read` — fill stake amounts.\n")
	b.WriteString("validators:\n")
	for _, in := range infos {
		fmt.Fprintf(&b, "  - server: %d\n", in.Server)
		fmt.Fprintf(&b, "    addr: %q\n", in.Address)
		fmt.Fprintf(&b, "    operator: %q\n", in.Address) // operator addr filled after operator keystore decode
		fmt.Fprintf(&b, "    bls: %q\n", in.BLSPubKey)
		fmt.Fprintf(&b, "    bls_pop: %q\n", in.BLSPoP)
	}
	return b.String()
}
